### ISSUE TITLE
Archive does nothing right now

### ISSUE THREAD

**Issue by shagath** [sindresorhus/caprine#1027]
It just doesn't do anything on my win10 pc. EDIT: At least from the conversation menu. Haven't tried other ways as I haven't got any new messages since then. 😅 

---

Caprine 2.34.0
Electron 5.0.6
win32 10.0.18945
Locale: en-US

**Comment by RJVB** [comment]
This has been the case for me too for a while now. Sometimes it works on my Mac (where I still run 2.15 because that build still supports my OS X 10.9).

I just found out that you can get back the old per-conversation context menu in the side bar when you maximise the window. Clicking the [...] widget gives access to Delete and Archive commands that actually work.

It'd be nice if it were not necessary to resize the window but one could resize the sidebar instead. There are other widgets that are inaccessible when the window is used in a regular size, like the "back" button when you've been into the "requested conversations" screen. But that's probably a different issue.
