### ISSUE TITLE
High CPU usage on Windows

### ISSUE THREAD

**Issue by lmr3796** [sindresorhus/caprine#1075]
Hi, I noticed that on Windows 10, repeatedly open and close window will push the CPU usage to 100%, not sure if it's due to some zombie process or so.

Environment: Windows 10, intel i7-3770, 32GB ram
Reproduce step:

0. Open Windows task manager to monitor
1. Pin Caprine messenger icon on the bar
2. Disable "Quit on window close" in Caprine
3. Repeatedly open caprine messenger window and close the window
4. In Task Manager, you'll see the number of background Caprine daemons increasing, each of which consumes noticeable CPU time, and the CPU usage getting higher and higher.

**Comment by shilangyu** [comment]
![image](https://user-images.githubusercontent.com/29288116/64573740-c1a11980-d36c-11e9-9a20-819206fa2a1a.png)
I can confirm the steps do indeed show the caprines stacking up.
Furthermore:
- The originally spawned caprine does not consume such amounts of CPU (it sits at 0-3% in my case while new instances use 20-30%)
- If I were to restore my closed Caprine from the active apps shelve, it will then open the same instance instead of creating a new one.

I see this 2 ways, either opening `caprine.exe` after one is already running is meant to spawn a new instance -> then the CPU usage should be fixed; or opening `caprine.exe` after one is already running should restore the original's window.

I hope this feedback helps :)

**Comment by lmr3796** [comment]
From my perspective, for message apps it's more common to have only one instance running, except for somebody might need the capability to chat using multiple accounts.  Slack does support the latter case, by adding capability of switching workspaces, which I think might not be cost-effective for caprine to develop.

Besides, if we take consistency into consideration, the app doesn't behave like this on Mac, so I think the best way is to restore the only running instance after opening the app again.

**Comment by n00bhax** [comment]
I still have this issue. Why was this closed?
