### ISSUE TITLE
App won't launch on Windows - Javascript error about vibrancy

### ISSUE THREAD

**Issue by Rifdhan** [sindresorhus/caprine#1079]
When I launch Caprine it gives me a dialog saying "A javascript error occurred in the main process", with a stack trace that seems to be about some vibrancy parameter being invalid.
![error](https://user-images.githubusercontent.com/8062299/64491672-1d11c100-d220-11e9-8b48-8cb90117f237.PNG)
Upon clicking "OK" the window closes and the app does not launch (no taskbar icon, etc), however task manager shows a Caprine process is still running.

I have tried uninstalling and reinstalling Caprine to no effect.

OS: Windows 10 x64
Caprine version: 2.37.0

**Comment by Rifdhan** [comment]
As a workaround for now, I have installed version 2.36.0 and it does not seem to have this issue.

**Comment by sindresorhus** [comment]
// @whitecrownclown

**Comment by qbone** [comment]
I get the exact same error when installing 2.38.0 on my system.

OS: Windows 10 x64

**Comment by whitecrownclown** [comment]
@sindresorhus
I have investigated this and my conclusion is that some configs have stale values for `vibrancy` which makes the validation fail and crash the application.

The fix for it would mean to delete/reset the configuration files.Unfortunately we cannot do this from the app since the validation is done before anything else. Maybe we could make use of [migrations](https://github.com/sindresorhus/electron-store#migrations)?

**Comment by GraionDilach** [comment]
Also happened when I bumped from 2.21 to 2.39. #1094 wasn't enough, apparently.

**Comment by Melkster** [comment]
To anyone with this problem: I was able to solve this issue by deleting `C:\Users\*user*\AppData\Roaming\Caprine\config.json` and then reinstalling Caprine.
