### ISSUE TITLE
Not really open source

### ISSUE THREAD

**Issue by Dalacu** [sindresorhus/caprine#1080]
It's so sad that you use that mining script that is fucking with my cpu. I've been using your app since last year but just yesterday, i've noticed that you have that shit built in the app. It's a shame, it's a trully shame.

So sad to see this, maybe users will start kicking off and you will remove it in the end.

**Comment by CvX** [comment]
Could you share a copy of the app you have installed? Where did you download it from?

**Comment by Dalacu** [comment]
[Official website.](https://sindresorhus.com/caprine/) My CPU is just feeling alive and cool again after uninstalling this crap.

**Comment by CvX** [comment]
What's your OS? Have you tried building and running the app from the source? Is there any difference in performance?

**Comment by Dalacu** [comment]
> What's your OS? Have you tried building and running the app from the source? Is there any difference in performance?

Tried that, I'm having this issues from the very first install, I did took a close look on my task manager and I could see that the app was causing my high idle temperature. I'm running Win 10 64bit, retail.

**Comment by Dalacu** [comment]
If you don't have acces to the whole source code, he might be hiding this from all you collaborators.

**Comment by CvX** [comment]
We all have the access to the source code, it's all in this repository. The builds are done semi-automatically on Travis CI, and then published here on GitHub.

There seems to be an issue with high CPU usage on Windows, already reported in #1075. I haven't seen the issue myself, I'll try with the latest version when I'll have access to a Windows machine.

Closing this, please follow #1075 for future updates in this matter.

Also, these accusations are a bit much, since so far there's absolutely no proof of any malicious code or intent…
