### ISSUE TITLE
Camera/Microphone access on Catalina

### ISSUE THREAD

**Issue by teomor** [sindresorhus/caprine#1128]
Camera and microphone access isn't available on my new Mac (Mac OS Catalina). The app doesn't ask for access so it doesn't show up in Security/Privacy tab (like WhatsApp does for example). No way to manually/explicitly add these (AFAIK).

---

Caprine 2.39.0
Electron 6.0.11
darwin 19.0.0
Locale: en-US

**Comment by elfensky** [comment]
I can confirm this as an issue, I can hear the caller fine, but since the app never requests microphone or camera access, they can't hear or see me. 
The camera is actually shows as non-existant, and the microphone is shows as "working" (toggle-able), despite the app having never requested (nor received) permission for it.

**Comment by Martus0** [comment]
I can confirm it is not asking about mic permission on Catalina.

**Comment by advicepyro** [comment]
Wanted to +1 this issue; just tried making a call and no microphone access came up. Great app otherwise!

**Comment by BassTester** [comment]
2.45 on catalina, just noticed the problem

**Comment by xiCO2k** [comment]
Same Here, Perfect app btw

**Comment by RishabSwift** [comment]
So there are no acknowledgements on this issue by the contributors nor any workarounds?

**Comment by coreybruce** [comment]
issue isn't quite fixed on Linux

Caprine version: 2.54.1
Manjaro Linux x64

Doesn't ask for permission for the mic when you want to record a voice message for example.
