### ISSUE TITLE
Menu bar is hidden on Windows

### ISSUE THREAD

**Issue by c99koder** [sindresorhus/caprine#115]
There's no way to access the settings on Windows because the menu bar is hidden and you've hidden the gear button that's normally part of the web UI.  Pressing the alt key temporarily shows the menu, but that's super confusing for most users.

**Comment by sindresorhus** [comment]
> Pressing the alt key temporarily shows the menu, but that's super confusing for most users.

That how Windows works.

**Comment by c99koder** [comment]
Huh, I've never seen a Windows app hide the menu bar like that. Doing some quick Googling, I guess ,the Windows 7 version of Explorer had an option to do that?  Definitely had me stumped for quite a few minutes trying to turn off the dark theme and turn on notifications.  Either way, there's no reason to be hiding the gear icon on Windows.

**Comment by workboot** [comment]
>> Pressing the alt key temporarily shows the menu, but that's super confusing for most users.

> That how Windows works.

Well do I misunderstand your answer? This is not standard behaviour for electron apps and not specific to Windows is it? The same thing happens on Fedora 23 and surely because of

``` javascript
autoHideMenuBar: true
```
in [index.js](https://github.com/sindresorhus/caprine/blob/2415e8d93bb505e5fd0b901f4e4d0ee3df1e7a33/index.js#L65). So is this a design choice for caprine?
In that case I agree with @c99koder that it is confusing for most users. At least a menu entry in the tray icon should be available to make it visible.
