### ISSUE TITLE
Some emoji's are not in the font used in the input box 

### ISSUE THREAD

**Issue by Haroenv** [sindresorhus/caprine#12]
For example `☺️` shows as a rectangle, sent and on messenger.com it behaves correctly however.

**Comment by sindresorhus** [comment]
I assume you used Safari on messenger.com. Chrome, which is what Electron and this app uses to render the app, seem to not support that emoji. Probably because it's using a variation selector: http://unicodelookup.com/#☺️/1

It's an issue with Chrome and out of my hands. I couldn't find a Chrome issue for this, but this seems related: https://github.com/nwjs/nw.js/issues/3489

Will keep this open until it's fixed in Chrome.

**Comment by Haroenv** [comment]
Ah, I assumed so, naughty Chrome then!

**Comment by sindresorhus** [comment]
Can no longer reproduce this in https://github.com/sindresorhus/caprine/releases/tag/v1.2.0.
