### ISSUE TITLE
Minimaze caprine

### ISSUE THREAD

**Issue by doklor** [sindresorhus/caprine#1210]
Double click or single click on minimazed icon of caprine on the taskbar doesn't reopen caprine to the window. Don't know that's an issue or just u didn't make it 

---

Caprine 2.41.1
Electron 7.1.1
linux 5.3.12-1-MANJARO
Locale: pl

**Comment by maxyvon** [comment]
Do you have an exemple of an app that does this?
I have tried with a few that I have on my Mac and none worked.

**Comment by vogu66** [comment]
Are you talking of the tray icon (next to things like the internet) or the program icon in the list of programs?

Also, it may depend on your desktop environment.

Does it still do that after updating your entire system?

**Comment by areographe** [comment]
Hey, I use the Cinnamon DE on Manjaro, and I've had this same problem for a while. The left- and right-click actions for the Caprine icon are the same: a menu with 'Toggle' and 'Quit'. All other system tray icons (from GTK2, GTK3 and Qt applications) show the main window of the app when left clicked, and a menu on right-click. Is this a Caprine issue or an Electron issue?

**Comment by vogu66** [comment]
Same OS with XFCE has had the same problem although I never found it too annoying. Maybe I'll try to pinpoint the origin of the problem somewhere next week, if I've got time. No promises from me though.

**Comment by vogu66** [comment]
I searched a bit and looked in the code too. The menu is indeed implemented in Caprine so it should work, however the [electron tray page](https://www.electronjs.org/docs/api/tray) shows this : 

"Platform limitations:
* On Linux the app indicator will be used if it is supported, otherwise `GtkStatusIcon` will be used instead.
* On Linux distributions that only have app indicator support, you have to install `libappindicator1` to make the tray icon work.
* App indicator will only be shown when it has a context menu.
* When app indicator is used on Linux, the `click` event is ignored.
* On Linux in order for changes made to individual `MenuItems` to take effect, you have to call `setContextMenu` again.
"

So I believe it's an electron problem, what with the "click" event that should be ignored. In addition, Discord and Skype (which according to [here](https://www.electronjs.org/apps) are based on electron although electron doesn't appear in the Manjaro dependencies -- probably something I don't know about is at work) and Steam (which is unrelated but was easy to test) all behave the same way (a single context-menu on left and right click).

At the very least, pamac-gtk (pamac-tray), which as far as I can tell only depends on gtk3 and not on libappindicator, and network-manager-applet which depends on libappindicator specifically, both can handle a different action on left and right click, so the limitation doesn't come from Linux, or Manjaro, or Xorg either.

-----

After a little bit more research, found this issue on electron : https://github.com/electron/electron/issues/14941

So it's definitely an electron bug, I think.

They also propose a potential workaround in the same issue, since apparently libappindicator causes the problem : 

https://github.com/electron/electron/issues/14941#issuecomment-680104395

Note that it relies on GtkStatusIcon, which is found in /usr/include/gtk-3.0/gtk/**deprecated**/gtkstatusicon.h ...

**Comment by rwwagner90** [comment]
@vogu66 if you figure out a workaround, I'd love to hear about it! From what I could tell, the workarounds listed were only for fixing your local copy of an Electron app, and not for fixing the app distributed to users.

**Comment by vogu66** [comment]
I believe you are right, although the workaround doesn't fix the application but electron, from what I understood, meaning all the apps using the library through electron would switch behaviour.

I haven't actually tried that workaround myself, not annoyed enough to bother with setting it up, and I'm not an expert either, so take that and what follows with critical thinking.

With that said,  I suppose it should be possible to have a patch that could be optionally distributed to users in their distribution, like an "electron patch" package or something that would apply the patch or have patched binaries and replace electron. Well, probably relatively easy to maintain that kind of stuff with the AUR but I don't know about other distributions. And I have no idea if a patch as a package would have the permissions to modify another program and if it could automatically be re-applied when the program is updated if it removed the file. 

And I believe it needs to be a patch and not a modification of the original code because of that whole "deprecated" thing for gtkstatusicon. Also, if the Electron developers wanted to fix it that way they would, since they are aware of the problem, as evidenced on the electron tray page.

And I'd love to play with this a bit, but I definitely won't have the time in the foreseeable future. If I ever get around to it, and get somewhere, though, I'll mention it here.

**Comment by dusansimic** [comment]
> After a little bit more research, found this issue on electron : electron/electron#14941

@vogu66 as I understood in comments in this issue, libappindicator left click event is ignored in Gnome so it would behave the same as in Unity DE (both lclick and rclick show context menu) https://github.com/electron/electron/issues/14941#issuecomment-453786629. This affects all distros that use Gnome.

Also mentioned in the comments, if you uninstall libappindicator and only have GtkStatusIcon installed, it will work as expected (lclick shows the app and rclick show the context menu).

Whatever the case may be in any specific distro or desktop environment, this issue is not caused in Caprine but in Electron and thus should be reported (or issue pinged again). I will close this now since it's not a Caprine issue however I really hope Electron figures this out.
