### ISSUE TITLE
Badge not working

### ISSUE THREAD

**Issue by danielfbnunes** [sindresorhus/caprine#1257]
On the last release (`2.43.0`), if **Hide names and avatars** is enabled, the badge doesn't appear with the current number of unread notifications. [OS: macos mojave 10.14.6]. Probably, this problem comes with one of the previous releases. Thanks 😉

**Comment by sindresorhus** [comment]
// @jyoo980

**Comment by jyoo980** [comment]
@danielfbnunes 

Sorry to hear that you've been having this experience. Can you clarify *where* exactly the badge isn't working? If it's the badge on the Touch Bar, then it's expected behaviour, since we currently hide avatars and names on the Touch Bar when this mode is enabled.

If the badge on the dock isn't showing the current number of unread notifications, then that's something I'd look into.

Let me know!

**Comment by danielfbnunes** [comment]
Hey @jyoo980 ,

The problem is with the badge on the dock. 

Thanks for the fast answer!

**Comment by jyoo980** [comment]
@danielfbnunes 

No problem! If it's a badge on the dock issue, I'm not entire sure if the scope of my work affected any logic related to the dock (I mainly worked on Touch Bar stuff), but I'll try to do some digging around anyway to see what's going on.

Does the same issue occur when **Hide names and avatars** is disabled?

**Comment by danielfbnunes** [comment]
@jyoo980 

No, the issue only occurs when **Hide names and avatars** option is enabled.

**Comment by jyoo980** [comment]
@danielfbnunes 

Thanks, I'll take a look and update this issue with anything I find!

**Comment by jyoo980** [comment]
@danielfbnunes @sindresorhus 

Hey!

After digging around a bit, I'm happy to report that I've found the bug. I'll try to fix it ASAP, but I'll post the necessary information here just in case someone else wants to give it a go 😀

The bug is in this [function](https://github.com/sindresorhus/caprine/blob/master/source/browser/conversation-list.ts#L154). It turns out that in order to trigger this [update badge event](https://github.com/sindresorhus/caprine/blob/master/source/index.ts#L412), we still need to send the list of conversations to be rendered, instead of just firing the private mode notification.

I can easily fix this by just sending the list of conversations to be rendered regardless of the private mode config flag, but this would cause a regression on the existing behaviour of hiding the names/avatars of people on the Touch Bar for Caprine on Touch Bar enabled MacBook Pros.

I'm totally open to just allowing this regression if it means getting a fix to notifications out faster, since the amount of people impacted by a regression on the Touch Bar would I think be lower vs the people who are affected by this notification. A fix that doesn't cause a regression would take longer and not be a one liner in my opinion. What do you folks think?

**Comment by danielfbnunes** [comment]
First, good job @jyoo980 . For me, this is not a critical issue and I think that, if possible, it only should be solved in the next release without any regression on the current development. Take your time, I'll be happy to see this solved in the next update 😄

**Comment by alexcosmin** [comment]
Hey fellas! 

First, great job with Caprine, just started using it a few minutes ago and it feels way better than the alternative I was using previously. Thank you!

Second, I'm also seeing this issue that the badge on the dock is not working for unread messages with **Caprine version 2.43.0** on **macOS Catalina 10.15.3**. For me, it also doesn't work when '**Hide names and avatars**' is disabled. Tried on 2 MacBook Pros, same OS version.
