### ISSUE TITLE
OLED theme

### ISSUE THREAD

**Issue by kingmustard** [sindresorhus/caprine#1258]
Basically a black theme.

Could this be an option, perhaps?

**Comment by whitecrownclown** [comment]
@kingmustard There is already a `Dark Mode` option that you can try.

**Comment by kingmustard** [comment]
> @kingmustard There is already a `Dark Mode` option that you can try.

That's not the same.

Grey doesn't save much power on an OLED screen as the pixel is still lit. Black saves 100%.

It's not asking for aesthetic reasons but for energy-saving ones :)

**Comment by mquevill** [comment]
I would also like this theme possibility. But as a temporary workaround, you can mess with some of the custom styles via File > Caprine Settings > Advanced > Custom Styles.

For instance, changing `--container-color: #000000;` and `--list-header-color: #000;` will change most of the background colors to a pure black.

**Comment by dusansimic** [comment]
The idea of custom styles (when that feature was added) was that users could write their own styles and share them with the community so everyone could just copy and paste the style and have a themed Messenger website. Adding an option is cool but I think it would be better that there are only two themes (light and dark, ones officially supported by Facebook) and everything else should be custom and third party. If at some point there are multiple custom themes shared, we could make a list of them. I'd rather close this for now since it's not in the scope of the project (it mainly in maintenance mode for now).
