### ISSUE TITLE
Videos inside gallery view don't show

### ISSUE THREAD

**Issue by NightMean** [sindresorhus/caprine#1279]
When I receive/send video and I click on it so it opens inside the gallery view it doesn't show nor does it have any playback controls. I can only hear the audio. I've been using v2.33.1 for a long time and I had no issue with this. 

---

Caprine 2.44.0
Electron 8.0.0
win32 10.0.18363
Locale: sk

**Comment by whitecrownclown** [comment]
This issue seems to happen on [messenger](https://www.messenger.com) as well. The preview returns [410](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/410) and the video won't play.

<img width="800" alt="Screenshot 2020-02-24 at 12 50 31" src="https://user-images.githubusercontent.com/8309417/75146735-5a9dd400-5704-11ea-9c68-e362d94fd6af.png">

**Comment by maxoku** [comment]
I can confirm that there is nothing. It's strange cuz in chat there is no thumbnail, in gallery is. In chat I can play it, but If I open it from gallery there is nothing at all, just emptiness.
I've checked the exactly same thing in browser and it works normally there.

**Comment by jonyroda97** [comment]
Same problem here
