### ISSUE TITLE
Avatars in chat are not perfect circle

### ISSUE THREAD

**Issue by gklka** [sindresorhus/caprine#1283]
Something went wrong in the last few days.

<img width="76" alt="Screen Shot 2020-02-20 at 11 08 58" src="https://user-images.githubusercontent.com/866694/74923679-81d96600-53d1-11ea-8017-17771a67cfc6.png">

---

Caprine 2.44.0
Electron 8.0.0
darwin 19.3.0
Locale: en-US

**Comment by whitecrownclown** [comment]
@gklka I'm not reproducing this in the same environment, do you mind checking if maybe there's some custom CSS you might be using? It would also help if you'd check [messenger](https://www.messenger.com), maybe you're whitelisted for a test (most likely).

**Comment by gklka** [comment]
I am not using any custom CSS. The avatars are circular on messenger.com. How can I provide you information about any ongoing A-B tests?

**Comment by whitecrownclown** [comment]
I don't think there's a certain way you can confirm you're in an ongoing A/B test.
I've managed to hack a way where your issue happens, but I still think it's a `messenger` side A/B test.

<img width="45" alt="Screenshot 2020-02-24 at 14 19 22" src="https://user-images.githubusercontent.com/8309417/75151984-abb3c500-5710-11ea-8505-163e4e99423c.png">

This happens when the `<img />` tag doesn't have a `max-width` set. This is the exact selector `._1t_q ._4ld- img`. Try opening the dev tools and refreshing with disable cache toggled to clear the cache. I'm assuming (I'm not sure if electron caches assets between sessions) you could have an old css asset version / might be stuck on an A/B test. That might explain why it doesn't happen on `messenger`.

Alas, If you can afford to reinstall please try that.

**Comment by gklka** [comment]
Reinstalling solved it, so it was something transitional which was cached probably. Thanks for the help.
