### ISSUE TITLE
caprine is sooooo laggy

### ISSUE THREAD

**Issue by fennecinspace** [sindresorhus/caprine#1354]
Hello, 

caprine is extremely laggy after only 2~3 minutes of use, switching between conversations sometimes blocks everything, and tbh i feel like it's killing my HDD, i don't know how it's related but when i leave it running for too long, my HDD starts making loud noise.

i have 4 TB (2 + 2) of space and 16gb of ram.
i'm on linux mint 19.2, on caprine 2.44 

can anybody recommend things that i could do to stop it from doing this. i used to use the old messenger for facebook linux app and i have never had these problems. i think it's the way caprine handles memory.

caprine is great. but it's soooo slow.

thank you.

**Comment by yllekz** [comment]
I've experienced the same. It tends to be a little heavy on CPU/RAM and reduces battery life on a Surface Pro.

**Comment by wereii** [comment]
I've been experimenting with [V8-compile-cache](https://www.npmjs.com/package/v8-compile-cache) for a while in my local build. 
I haven't really noticed some awesome boost, but startup feels definitely faster. My machine is a bit bulkier on the resources [i7-7700HQ CPU @ 2.80GHz, 16gb Ram, SSD] so yeah, haven't really had too much of problems before then, except for some freezes - can't remember if they still happen since I am using the cache. ¯\_(ツ)_/¯ 

Pushed the caprine with v8 here: [wereii:speedups](https://github.com/wereii/caprine/tree/speedups) so if someone wants to test.

To build it, just `git clone` the repo and then in the folder do `npm install & npm dist`.
Though this will build installable/executable for all target platforms on all target OSs. So If time is of the essence then
- `npm install` in the repo directory
- `npm tsc`
- `npm electron-builder --linux`, or instead with `--macos` or  `--windows`
- The executables will be in `dist/` folder.

**Comment by alekksander** [comment]
has anyone tried this one?
@wereii  could You plase update to newest version?

**Comment by wereii** [comment]
@alekksander Updated the [speedups branch](https://github.com/wereii/caprine/tree/speedups) to current [2.47.0](https://github.com/sindresorhus/caprine/tree/v2.47.0).
