### ISSUE TITLE
There's no option for deactivate the autoupdate.

### ISSUE THREAD

**Issue by Loughty** [sindresorhus/caprine#1364]
I can't find anything in the options. The fact that these updates are silent and forced is quite annoying for me, I have no way to avoid them? I don't want him to download anything at all in the background without my permission.

**Comment by dusansimic** [comment]
What OS do you use and what installation method do you use? From what I know, Caprine has intentionally added auto update since there were a lot of issue reports for older versions of Caprine and an average user won't go to releases page and download a new release. By auto updating, we make sure users have all the latest bug fixes so there would be less duplicate issues. Also https://github.com/sindresorhus/caprine/issues/936#issuecomment-502324014 here is a comment by the maintainer regarding this issue. I'll close this now.

**Comment by Loughty** [comment]
Sorry, my answer comes very, VERY late, I delete my facebook account and don't login to github all this time. I hope that my comment won't angry anybody for necrobump or something like that.

For that time I was using Windows 7 SP1 64bits. If my opinion give you some help, there's two type of users:
- Whos don't care anything and prefer that the program do everything without notify him, just install and use.
- And whos care everything and prefer to see what the program do, what comes with the new update before installing it, etc..
A simple option to activate or deactivate the autoupdate function could makes happy both of them, just make it on by default.

Also, there's other considerations, like the users of a limited ISP plan that wants to reduce the frequency of the updates of his programs for save some money. Or the users with a very poor bandwidth connections and the force autoupdate interfere with the functions of the program itself (can't login o send messages, because the update are consuming all the bandwidth, for example).
