### ISSUE TITLE
Advanced Settings / Custom Styles freezes the whole screen

### ISSUE THREAD

**Issue by FerencBuzas** [sindresorhus/caprine#1376]
---
Select from the menu:
  File / Caprine Settings / Advanced / Custom Styles

This brings a modal dialog with picture buttons of editors, but none of them can be selected.

The whole screen freezes; the only measure I found was to press Ctrl/Alt/F1 to get a terminal and kill the caprine process.

Caprine version: do not know, Help/About does not give any relevant information
Linux ubuntu-18.04

**Comment by mquevill** [comment]
The `Custom Styles` option in the menus is set up to open `~/.config/Caprine` with your default text editor. Ensure that you have a default/preferred application set to open source code (`.css`) files that works as expected if you try to open other `.css` files.

Furthermore, how was Caprine installed (snap, deb, etc.)? Please try updating to 2.47.0 (even if it's already installed) to ensure you are on the latest version.

**Comment by FerencBuzas** [comment]
Hi,

the bug I reported is not a blocker issue, even though it is a bit hard to
get back from the dialog which offers to select an editor. Yet I know that
I should avoid that function in the menu.
I cannot say which version I have: Help / About is not really informative.

Anyway, Caprine is a fine program, to stay connected with people without
having to use Facebook.

Thank you! :)

Ferenc

Am Di., 23. Juni 2020 um 06:13 Uhr schrieb Michael Quevillon <
notifications@github.com>:

**Comment by dusansimic** [comment]
As already explained, Caprine opens a file in the system defined editor. If the editor is not defined, a modal you described opens in order to chose which editor to use. That is a system modal, not a Caprine one. If that modal freezes, it means it's the issue with the distribution you use, not Caprine. As already explained, you could define an editor for opening CSS files (for example create an empty file with a `.css` extension and you should be able to set a default program for opening it through your desktop environment settings, please refer to the documentation of your desktop environment). I'll close this report since it's not a Caprine issue.

**Comment by FerencBuzas** [comment]
Hi Dusan,
Now I realized that although the system modal dialog freezes the whole screen for the mouse, an item can be selected with the keyboard.
I use Ubuntu without changing any special setting so it may be a small bug in the OS.
Thank you anyway! :)
