### ISSUE TITLE
send wave

### ISSUE THREAD

**Issue by baptx** [sindresorhus/caprine#1380]
I noticed the web version of Facebook Messenger removed the wave feature.
Is it possible to send a wave with your app? Maybe the feature is just hidden in the web version and the API call still works.
If someone saved an HTTP request or managed to get it from a previous version of the mobile or desktop app (with a tool like mitmproxy), please share.

**Comment by dusansimic** [comment]
AFAIK wave is only possible when a chat is created and if it's not possible anymore, then we can't really bring it back. I think that "wave" feature was actually just a fancy button for sending a wave emoji which is easy to do with the emoji picker. Try that out and see how it looks.

**Comment by baptx** [comment]
@dusansimic For information, it was possible to wave at people even after a chat is created: https://www.quora.com/How-do-I-wave-to-people-in-Facebook
It is a bit different than just an emoji since the other user was able to to reply to the wave by clicking on a button (like the poke feature).

**Comment by dusansimic** [comment]
It seems like that feature was removed from Messenger. I can't find it on my phone or Messenger.com. Since it doesn't exists on Messenger.com, it wouldn't by default exist on Caprine. I doubt that there is a way to wave now since it's removed on every platform so I'll close this. If anyone else shows any interest in working on this, PRs are very welcome but right now I don't think we have resources to support a feature that has been removed from Messenger.

I'm sorry about this but right now we are overwhelmed by issue posts which are mostly outdated or duplicates so this could be revisited if there is any more info on this topic.

**Comment by baptx** [comment]
@dusansimic I just saw that the wave feature was present on the project: https://github.com/sindresorhus/caprine/pull/1146
Doesn't it mean that you used an HTTP request to send waves in your code? (in this case, we could find the request in the commits history)
Or you were just integrating a web view of the official Facebook Messenger code?

**Comment by dusansimic** [comment]
Caprine is just a wrapper around Messenger.com with a lot of other features added. This means that waves were handled by the Messenger.com website itself. The issue you linked was a fix for the dark mode which is a Caprine feature.

So since we didn't handle the waves, we can't really do anything here. If there is still a way to send waves to people, that'd be cool to add but AFAIK, that was all handled by Messenger.

**Comment by baptx** [comment]
@dusansimic I got the wave feature working directly with the HTTP request, hopefully some people saved it before being hidden on Facebook Messenger :)
This was the second result on DuckDuckGo when searching `facebook messenger api "wave"`:
https://fbchat.readthedocs.io/en/stable/api.html#fbchat.Client.wave
Basically, we just need to add these POST parameters to the HTTP request used for sending messages:
```
lightweight_action_attachment[lwa_state]=INITIATED
lightweight_action_attachment[lwa_type]=WAVE
```
You can replace INITIATED with RECIPROCATED if you want to reply to a wave.
More information: https://github.com/Schmavery/facebook-chat-api/issues/541
