### ISSUE TITLE
Large Memory Usage

### ISSUE THREAD

**Issue by sjisma** [sindresorhus/caprine#1427]
Caprine will take all of my memory and graphics drivers eventually break.
I don't know if this is Caprine or just messenger being bad. If I use messenger on my browser, it lags, but I can force refresh clearing the cache and it just works again.
Running on an Asus Helios 300 GTX 1060, 16GB memory, 256GB NVMe sotrage
Default settings for Caprine and changed settings end up with large amounts of memory being used.

Process:
1. Leave caprine running
2. Wait

---

Caprine 2.50.0
Electron 10.1.1
win32 10.0.18362
Locale: en-US

**Comment by dusansimic** [comment]
There is a menu option for quick relaunch of Caprine (File -> Relaunch Caprine). Still, I will look into this issue. Thanks for reporting it!

**Comment by xChickens** [comment]
This issue has been happening quite often to me. Not sure how I can log it, but this is task manager.
![image](https://user-images.githubusercontent.com/2402510/98438241-c4e18380-209d-11eb-8d9c-e51059c98c76.png)

**Comment by pktiuk** [comment]
This problem was already reported here: https://github.com/sindresorhus/caprine/issues/1244

**Comment by dusansimic** [comment]
@xChickens for how long did you have Caprine running?

These reported issues are in most of the cases traced back to large memory usage by Messenger.com itself. The website stores all of the images in memory for quick access. This can be checked in the DevTools (F12) in the sources tab. They might be small in size but the sizes pile up and after running Caprine for a long time, it is expected to have large memory usage. Sadly, we can't fix this in a safe way (without creating more problems) so I would recommend using the restart Caprine option (`File -> Relaunch Caprine`). This would just quit Caprine and start it again.

**Comment by xChickens** [comment]
> @xChickens for how long did you have Caprine running?
> 
> These reported issues are in most of the cases traced back to large memory usage by Messenger.com itself. The website stores all of the images in memory for quick access. This can be checked in the DevTools (F12) in the sources tab. They might be small in size but the sizes pile up and after running Caprine for a long time, it is expected to have large memory usage. Sadly, we can't fix this in a safe way (without creating more problems) so I would recommend using the restart Caprine option (`File -> Relaunch Caprine`). This would just quit Caprine and start it again.

I don't think that I've necessarily seen a connection between the time I leave it running and how much memory it takes up. Most of my experience is that the memory that it takes up is typically pretty low, and then just for some random reason the memory usage takes up practically every byte. And it has only specifically started occurring since my last update of the app (the icon changing from a fully blue image to one with a white background). Additionally, it only occurs primarily with the background caprine processes, not the active window itself, so actually most of the times it has occurred for me the app is minimized in the tray. Essentially, in regards to time, I've had periods where there can be hours (12+) without anything happening, and then a time where about 1-2 hours after it occurring once, it occurs again. I'm sure there is a cause, but I don't know really what it is at all, and I don't know how to easily log it.

**Comment by xChickens** [comment]
Update, some more details are that it happens regardless if the Caprine window is in the foreground or minimized into the system tray, and ending the process taking all memory doesn't not even make the program break. It just gets rid of the problem. Additionally, if I close other programs to make more memory, it will begin to consume that free memory as well. More pictures:

Foreground window:
![image](https://user-images.githubusercontent.com/2402510/100305668-61d56500-2f56-11eb-8fc7-b573858c7935.png)


System tray:
![image](https://user-images.githubusercontent.com/2402510/100305643-584bfd00-2f56-11eb-8781-8276ca8ab0a0.png)

**Comment by savage93** [comment]
I've just realized that the same issue is probably happening to me as well, definitely looks like a memory leak.
![caprine](https://user-images.githubusercontent.com/30925624/102288320-282fc280-3f34-11eb-8d76-6be8f257b4f6.png)
