### ISSUE TITLE
Caprine Will Not Luanch After Upgrading to Fedora 33

### ISSUE THREAD

**Issue by LinuxFanboy745** [sindresorhus/caprine#1432]
I waited a day after Fedora 33 was released to upgrade to it, after upgrading, Caprine will not even launch. I fully removed it from my system and re-installed it but it will not launch. I installed it using Snap, so the version I have right now is 2.5.1 .

**Comment by dusansimic** [comment]
What installation method did you use for installing Caprine on Fedora? AppImage or something else?

**Comment by LinuxFanboy745** [comment]
Snap

**Comment by dusansimic** [comment]
So you installed it on Fedora with Snap, I thought you meant that you installed it with Snap after some other package format? AFAIK Fedora does not support snap officially since it's built to work with Ubuntu based distros and Snap itself is not very good as a package manager. If you don't have any special reason to use Snap on Fedora, try using AppImage version. That's how I use Caprine.

Regarding the packages for Fedora, @sindresorhus what do you think about adding RPM as a target in electron builder? It's supported and work fairly well. I know it's not in plan to extend Caprine features anymore but this could make it easier to install on Fedora. Another option would be `tar.xz` target which can be used on any distro with required libraries (required by Electron).

**Comment by LinuxFanboy745** [comment]
nope, I hate using snap, I've just been using it for easy. As for an rpm version, I would agree, it would a good idea.

**Comment by LinuxFanboy745** [comment]
And appimage is great and all, but It would be better for it to be installed instead of me having to sing into it every day

**Comment by dusansimic** [comment]
You can stay signed in with AppImage too. Check out [appimaged](https://github.com/probonopd/go-appimage) which creates an icon for AppImage based app. I usually put all my AppImage apps in `~/Applications` (also put appimaged there) and just run appimaged once, it'll be installed onto your system and you can use all AppImage apps just like any other app.

I'll write a PR for RPM and tar.xz target in case maintainer wants to support it.

**Comment by LinuxFanboy745** [comment]
I don't see why not, it would open doors to another distro

**Comment by dusansimic** [comment]
Okay, after going through closed issues, i found this https://github.com/sindresorhus/caprine/issues/1411. Seems like there won't be any new formats.

**Comment by LinuxFanboy745** [comment]
woow... ive been using caprine for a little over a year and thats it ? Alright then

**Comment by LinuxFanboy745** [comment]
I dont understand why an rpm cant be made, I'm not asking for much here

**Comment by dusansimic** [comment]
For every package format, there are different build procedures which may or may not result in a stable build (there are some problems with icons on deb and rpm packages, AppImage now has an icon but it is distorted in app switching dialog) and every package format needs to be maintained. We don't have resources to do that now.

However, any help regarding this would be very much welcome. For example, there is caprine package in Arch repositories which is not maintained by us so someone can make RPM builds which won't be official but they will be available for users to use. This would be much appreciated.

**Comment by LinuxFanboy745** [comment]
As much as I would to do that, im not a dev or a coder, just a user and repairer, so thats above me. I see this as not opening the doors for people with different distros, if you didn't want those doors in the first place, then just stick with mac.
