### ISSUE TITLE
Caprine features not working

### ISSUE THREAD

**Issue by NlGHT** [sindresorhus/caprine#1439]
I'm using up-to-date latest Arch Linux.  Just got this issue which I have never seen before today:
![image](https://user-images.githubusercontent.com/36537208/98717947-0a4bcc80-238e-11eb-87b1-5e63c92adc12.png)

The actual messenger site/interface loads correctly but none of the caprine features work (dark mode, messenger settings, new conversation).  Couldn't find any errors in the console, there were just warnings as so:
![image](https://user-images.githubusercontent.com/36537208/98719100-9ca0a000-238f-11eb-843c-69165498a711.png)

**Comment by dusansimic** [comment]
Are you able to change the options or Caprine is not responding to changes in the options?

**Comment by NlGHT** [comment]
I am able to change caprine-specific things like for example toggling the tray.  However anything related to actual messenger does not appear to work.  These are features like:  Dark mode, File->Messenger Settings, Conversation->Find in conversation, Conversation->Search in conversation etc.  From the outside, it looks like any Caprine->Messenger interactions don't work.  Everything in actual messenger works and everything in just Caprine works still.  There is of course still the popup as shown in the first screenshot saying "Content is no longer available", but after clicking ok, messenger is fully usable but stays light mode.

**Comment by dusansimic** [comment]
I believe that popup is not related to unwanted behavior. The mentioned popup is displayed when Messenger couldn't load some content (image or video) since it was removed or was unreachable. That happens to me from time to time but not very ofthen. It's a Messenger issue, not a Caprine issue.

However the problem with the dark theme and custom Caprine features not working is something else. This usually happens when Messenger interface is updated. If you've received a notification about any new features, updated interface or something like that, that could be the problem.

**Comment by baq-86** [comment]
@dusansimic , answering to your questions (https://github.com/sindresorhus/caprine/issues/1447#issuecomment-730045818):
> Hi! Is there some error message displayed? Are you using custom styles? Is there a specific way that I can reproduce this since I'm running latest version of Caprine and I have no problems whatsoever. Also, how did you install Caprine?

- There is no error message displayed.
- I'm not using custom styles - only built-in dark mode.
- I didn't do anything specific to make this all happen. Simply, one day everything worked fine and the next day massenger.com changed and Caprine functions no longer works. This change of messenger.com is delivered not to everyone at the same time so it is possible that you are still using "the old" messenger.com (which works ok with Caprine).
- I installed Caprine from .deb package (https://github.com/sindresorhus/caprine/releases/download/v2.51.1/caprine_2.51.1_amd64.deb).

Hope this helps.

**Comment by dusansimic** [comment]
Thanks for that info @baq-86. If there was a change to Messenger.com, I'll have to wait for it before I can try to fix it. @CvX do you have any info on this? Is there a forum where there's updated about messenger.com?

**Comment by NlGHT** [comment]
So mine has magically just started working again, fully functional today.  Last night it wasn't.  This is so weird.  When it was broken however, similarly to @baq-86:
- No errors other than "This content is no longer available", just the console log as I showed in the screenshot above.
- No custom styles
- Nothing specifically I did to cause it to happen.  Nothing has changed on my end for it to happen as far as I'm aware.  I have noticed that @baq-86 and me are close country-wise with Denmark and Poland so maybe the issue is related to some sort of region difference.
- Caprine installed through pacman with Arch Linux official community repo (Built 22/10/2020) (Electron built 24/10/2020)

To get it working again I am pretty sure I changed nothing :(  I did do a full system upgrade but neither caprine nor electron have had updates since december.

**Comment by dusansimic** [comment]
This seems to be an ongoing issue due to Facebook rolling out the new Messenger.com UI. For some people it might revert back to the old UI which would in turn suppress the issue but not fix it. I'd like @sindresorhus and @CvX opinion on this. How should we proceed with this?

I was thinking of finding out who has access to the new UI and asking the nicely 😁 to download the HTML of the page so we could work on fixing issues that way until it's released for some of us.

**Comment by baq-86** [comment]
Hi! For me, today Messenger.com reverted back to the old UI. All Caprine features work back as it was before.

**Comment by BloodRaven0** [comment]
@dusansimic [Here](https://techcrunch.com/2011/09/21/how-to-go-back-to-the-previous-facebook-interface-while-you-still-can/?guccounter=1&guce_referrer=aHR0cHM6Ly9kdWNrZHVja2dvLmNvbS8&guce_referrer_sig=AQAAAFXqpP08lRKL5wEt38iUi4lLzEcaxwI2nvK-X9mTdTfzhHJgu4DtMgO1k7va7H15JZHz8i00vosj7E3K6WpsMvZaroWzTKT93DRdOo-e8S1wMlFhbK14VefZguYKj6bumqZTcX_bt4pTGMq18P-oU-7WifeRlYf0m2LUkrb_Ck86) is an article that describes how to go back to the old interface. While it did not work for me (I was already at UK, this might be the reason why my interface update got delayed), it could work for you to switch to the new UI. Try to fool around with the regional and language options of your FB account, see if it works.

**Comment by dusansimic** [comment]
@BloodRaven0 thanks for the input! However it won't work that easily.

>Here is an article that describes how to go back to the old interface.

This seems to be a quite old post and probably won't work today. I've just tried it for a number of regions and didn't seem to work. I think the UI roll-out is user based, not region based since some of my friends who live in the same region as I do got some UI updates before I did.

>EDIT: also, Here is an article that says you can just simply press the dropdown arrow in the FB main screen and switch to the new UI, simple as that.

This options switches the Facebook UI but not the Messenger UI. Messenger UI already started rolling out the new (more rounded) design but it seems there have been some major updates to the design which are unrelated to the Facebook ones.

**Comment by fliker09** [comment]
If anyone interested - added this to custom.css and my eyes stopped bleeding:
`html {
    background-color: #ddd;
    filter: hue-rotate(180deg) invert(100%) !important;
}

body {
    background-color: #ddd;
}

iframe, img, video, canvas {
    filter: hue-rotate(180deg) invert(100%) !important;
}`

**Comment by vogu66** [comment]
For debugging purposes, those are the error messages with the new style. Not sure if they were already there before.

```
laipN-Swfcp.js?_nc_x=El8sMBma0Vo:59 ErrorUtils caught an error:

epoch mismatch

Subsequent non-fatal errors won't be logged; see https://fburl.com/debugjs.
b @ laipN-Swfcp.js?_nc_x=El8sMBma0Vo:59
VM795 renderer_init.js:111 Electron Security Warning (enableRemoteModule) This renderer process has "enableRemoteModule" enabled
    and attempted to load remote content from 'https://www.messenger.com/t/**********************/'. This
    exposes users of this app to unnecessary security risks.

For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.
(anonymous) @ VM795 renderer_init.js:111
VM795 renderer_init.js:111 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
    Policy set or a policy with "unsafe-eval" enabled. This exposes users of
    this app to unnecessary security risks.

For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.
(anonymous) @ VM795 renderer_init.js:111
DevTools failed to load SourceMap: Could not load content for https://www.messenger.com/usr/lib/caprine/node_modules/uri-js/dist/es5/uri.all.js.map: Unknown error
```

> I was thinking of finding out who has access to the new UI and asking the nicely grin to download the HTML of the page so we could work on fixing issues that way until it's released for some of us.

I do, and I may help you (for now at least, I guess it may revert any time), but I don't want to put that online, because copyright and  all that, and also I'm not entirely sure I can remove all the personal elements from the page. I guess I can use the mail address on your profile, if this is still relevant?

Also, I may need a pointer or two to get something else than the raw html out of electron (I know on Firefox you can get a reconstruction of the css, but there is at least one button that appears in Caprine and not Firefox, probably due to Caprine being chrome-based, so it's probably better to get the source directly from Caprine)

**Comment by dusansimic** [comment]
Hi @vogu66!

> I do, and I may help you (for now at least, I guess it may revert any time), but I don't want to put that online, because copyright and all that, and also I'm not entirely sure I can remove all the personal elements from the page. I guess I can use the mail address on your profile, if this is still relevant?

Thanks! It is relevant. You can email me the source of the page. Regarding the extracting the raw HTML, we've discussed that in #1452. We can use a script that will copy the HTML, remove any sensitive data and copy the edited HTML to clipboard. There have been some problems regarding that script since it removes some useful information. I've made a variation of that script and we could try it out. If you are interested, send me an email and I could walk you through how to extract the HTML and view the results. The instructions on how you use the script are the same as in the issue I mentioned. I'd like to continue this via emails since it's not directly related to the issue so we won't bloat the thread 😁. Thanks again for coming forward to help out!

**Comment by maxoku** [comment]
For me it started yesterday. No dark mode, no notifications or other Caprine functions like resizing. Only spellchecker works.
I don't like this new UI. The only good thing is the green dot if someone is active. The rest sucks.
I hope it will be fixed and maybe some new functions to handle this new UI.

**Comment by baq-86** [comment]
> Hi! For me, today Messenger.com reverted back to the old UI. All Caprine features work back as it was before.

Today, after almost 3 weeks, the new UI came back...

**Comment by maxoku** [comment]
No notifications is the most problematic, I don't know when someone sent message to me :/.

**Comment by Octanas** [comment]
> Hi! For me, today Messenger.com reverted back to the old UI. All Caprine features work back as it was before.

Anything you did or it just happened? Mine just changed to the new UI and I'd really like to go back.

**Comment by baq-86** [comment]
> Anything you did or it just happened? Mine just changed to the new UI and I'd really like to go back.

I did nothing. It just happened, exactly like it was the last time, about 3 weeks ago. I'd like to go back, too.

**Comment by robinsrk** [comment]
I am facing this issue since yesterday. Does anyone know any fix for this?

**Comment by ammanley** [comment]
Been reading through a couple of these Issues that have cropped up since the new Messenger updates rolled out. Do we have any idea what the core issue is with `Privacy` options not working/is it even possible with their new API?

**Comment by RedDragonWebDesign** [comment]
Maybe consider pinning this bug report.

Maybe consider renaming this to "Multiple bugs caused by Facebook messenger changing their UI" or something similar.

I check back every few weeks hoping for a new release. Caprine was imo the best Facebook Messenger desktop app before these new bugs. I have high hopes that things will be fixed.

**Comment by mzso** [comment]
Not sure if its new design related, but the messenger window is completely unresponsive after hibernating Windows. I have to close it and re-open it again.

**Comment by maxoku** [comment]
After update the dark mode returned, but it's not working after restart. I need to disable it and enable again to make it work.
There are still no notifications of any kind. No badge on taskbar or tray icon. The only way to know if there is a message is to hover the icon and see if there's a number in the title e.g. `(1) Messenger`.
Autoplaying is the most annoying. I know it's the function of new UI, but I hope Caprine would be able to disable it.
Resizing doesn't work on sidebar. It would be nice if Caprine would make those avatars smaller like it was before.
`Show Message Buttons` function seems to not have any effect.

**Comment by dusansimic** [comment]
@maxoku [here](https://github.com/sindresorhus/caprine/pull/1514) is the list of things we have fixed/not fixed so far.

The issue about dark mode not being turned on automatically after app is started is already reported in #1525.

The issue with notifications is discussed [here](https://github.com/sindresorhus/caprine/issues/1522#issuecomment-757998055). Essentially, we cant fix it for now because  the notifications don't exist in the first place.

The badge issue is being worked on. There is no ETA on that for now.

Auto playing videos is not being worked on for now.

Resizing the left sidebar is automated when the window gets small enough but the feature of manually selecting the width is not working for now. This is also not being worked on.

Any help from anyone is very welcome at this time since we have limiter resources and manpower.

**Comment by maxoku** [comment]
Badges of unread messages stopped working again week ago. The same with tray icon not changing color with new messages.

**Comment by dusansimic** [comment]
Closing this issue in favor of other issues for specific problems. If there are new problems that aren't already reported, please open a new issue with a detailed description.

**Comment by maxoku** [comment]
Notifications returned, but badges of unread messages still don't work.

**Comment by mzso** [comment]
[**@maxoku**](https://github.com/maxoku) commented on [2022. márc. 20. 14:14 CET](https://github.com/sindresorhus/caprine/issues/1439#issuecomment-1073249636 "2022-03-20T13:14:50Z - Replied by Github Reply Comments"):
> Notifications returned, but badges of unread messages still don't work.

Really? I didn't notice any. Are you using a beta build or something?

**Comment by maxoku** [comment]
@mzso 
> Really? I didn't notice any. Are you using a beta build or something?

There was an update today v2.55.3 that brings back notifications (preview of the new message).
>  BTW, what do you mean by the badges?

I mean when there is an unread message there is (suppose to be) a badge with number (in a red circle) on the taskbar icon and tray icon changes its color from grey to blue.

**Comment by mzso** [comment]
@maxoku 
I didn't see any notifications when someone messaged me.
