### ISSUE TITLE
Caprine 2.51.1 errors after starting and connecting to messenger

### ISSUE THREAD

**Issue by cherkie** [sindresorhus/caprine#1448]
After upgrading to 2.51.1 I have received an error when starting Caprine (attached).

I have checked if I can connect to messenger via browser and same error appears. I have removed all cached data tied to facebook.com and messenger.com from my machine and it still persists. (I am new to posting issues on github, unsure what else should I add - looked around for any logs but couldn't find anything in default install dir `/opt/caprine/`)
---
![caprine2_51](https://user-images.githubusercontent.com/36137163/99676539-efa5e180-2a78-11eb-9355-a7b0f8e39607.png)

Caprine 2.51.1
Electron 10.1.5
linux 5.7.0-3-amd64
Locale: en-GB

**Comment by dusansimic** [comment]
Do you have your Facebook account deactivated? [Here](https://www.facebook.com/help/214376678584711/) is a description of what I mean.

**Comment by cherkie** [comment]
> Do you have your Facebook account deactivated? [Here](https://www.facebook.com/help/214376678584711/) is a description of what I mean.

Yes, I have my Facebook account deactivated. I've had it for years while I've been using messenger and definitely had it deactivated for the past ~6 months when I've been using Caprine. 

While I'll wait for you to reply I'll reactivate, try to log in and then deactivate. I'll post if it'll help.

**Comment by dusansimic** [comment]
There was an issue regarding deactivated accounts reported a few days ago. This seems to still occur. Also there are some issues regarding dark mode and other Caprine features on some devices which seems to be due to new version of website being rolled out.

Do you see any difference in the interface regarding the "new version of messenger"? This would help us understand if there are some significant UI changes which could break current Caprine features.
