### ISSUE TITLE
Right click on windows taskbar shows Electron

### ISSUE THREAD

**Issue by imtaurus94** [sindresorhus/caprine#145]
I found out that a right click on the Caprine icon in the windows taskbar shows Electron.

I know this is what Caprine is built on, apparently, the original name is still somewhere in the code
![capture](https://cloud.githubusercontent.com/assets/17530304/20997933/ebc6b976-bcd7-11e6-8f02-fa20d7b47a01.PNG)

**Comment by kartsims** [comment]
This seems to be due to this issue https://github.com/electron/electron/issues/4241

Have you worked on Electron apps on your computer before ?

The solution seems to implement the [`app.setAppUserModelId`](http://electron.atom.io/docs/all/#appsetappusermodelidid-windows) method but I am not sure exactly where and can't get to a windows computer right now.

**Comment by Chamuth** [comment]
Yes, there is an Electron in the application name. I don't develop with Electron, Electron is not even installed.
![2017-01-02](https://cloud.githubusercontent.com/assets/12496229/21583529/7dcb89ee-d03a-11e6-9038-d910203dfce5.png)

**Comment by Chamuth** [comment]
I Fixed it with ResourceHacker. [http://www.angusj.com/resourcehacker/#download](url), Now take a look at this, you can change the copyrights information, company and many other things. Just edit the Version Info file.
![2017-01-02](https://cloud.githubusercontent.com/assets/12496229/21583570/31f652fe-d03c-11e6-941d-fce9ab335b44.png)

**Comment by sindresorhus** [comment]
Should be fixed in https://github.com/sindresorhus/caprine/releases/tag/v2.0.0
