### ISSUE TITLE
Feature request: Download/Export Messages and Delete All Messages

### ISSUE THREAD

**Issue by gr01d** [sindresorhus/caprine#1457]
This is not an issue but a feature request, I would like to have this is possible. First an option to download faccebook messenger messages to maybe html or json, possibly including the media assets too. And another one is a button to delete all messages automatically for a particular conversation (some thing like Undiscord (https://github.com/victornpb/deleteDiscordMessages).

**Comment by dusansimic** [comment]
Hi!

As for downloading Messenger chats, that's possible through Facebook. There is a Download Your Information page (https://www.facebook.com/help/212802592074644/?ref=u2u) where you can select which information to download. To download only Messenger chats and images, just select messenger and select the time span to download. This will download all of the chats in that time span. We will not be implementing this feature since it already exists as part of Facebook.

As for deleting the messages, you can delete the whole conversation if that's what you're aiming for. You can do that by clicking on three dots next to the chat name in the chat list and clicking on the Delete option. A modal will prompt with the question if you're sure you want to delete the chat. By clicking Delete, messages will be deleted from your history.

I hope this helps. Let me know if that works!

**Comment by alxpettit** [comment]
This is insufficient IMO. What if someone sends you harassing messages but maliciously deletes them all? Having a local copy that doesn't exist at Facebook's whim is pretty important in my opinion.
