### ISSUE TITLE
VA-API support ?

### ISSUE THREAD

**Issue by Tuxino88** [sindresorhus/caprine#1479]
is it possible to have support for video decoding from GPU on Wayland (VA-API)?

**Comment by dusansimic** [comment]
Hi @Tuxino88! Sorry for a late reply. This unfortunately is not something we can fix. VA-API support (or any kind of hardware acceleration for that matter) needs to be supported by Chromium. Since Chromium won't support that by default rather make it optional for users to build Chromium themselves with HA support, Electron won't add it and won't support it. Because Electron doesn't have HA support, then in turn, we can't have it.

In [this](https://www.omgubuntu.co.uk/2018/10/hardware-acceleration-chrome-linux) article it's suggested that Chromium doesn't plan on adding support by default but they do have and option to build it with HA support.

In [this](https://github.com/electron/electron/pull/19736) issue, Electron developers said that they won't add support to Electron unless Chromium adds it as they want to be as close as they can be to the upstream Chromium.

Since this is not a Caprine issue and once the support is added to Electron we will get the support for HA, I'll close this issue.

**Comment by dusansimic** [comment]
I've just realized that I haven't completely answered your question. As you might have deduced, you **can** have support for VA-API in Caprine but you have to build Electron yourself with support for it and in turn build Caprine with that version of Electron. If you're not interested in building it yourself the only option is to wait for Chromium to add support by default.
