### ISSUE TITLE
Linux installer

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/caprine#15]
Looks like we can use [`fpm`](https://github.com/jordansissel/fpm) to easily create a `deb` package.

Example: https://github.com/Aluxian/Facebook-Messenger-Desktop/blob/29b493f443ce2dc385ed62437a5c9013e4e45408/gulpfile.coffee#L107
## 

@tschuy Interested?

**Comment by tschuy** [comment]
Definitely, I'll take a look tomorrow evening. Thanks for the pointer!

**Comment by forivall** [comment]
After seeing caprice mentioned in module requests, I made an Arch package on the aur: https://aur.archlinux.org/packages/caprine-bin/

Hopefully you can compare the `PKGBUILD` that fpm creates. I probably should have it installed under `/opt` instead of `/usr/share`, but atom installs under /usr/share. so :unamused: 

@tschuy ping!

**Comment by sindresorhus** [comment]
I just discovered https://github.com/unindented/electron-installer-debian and https://github.com/unindented/electron-installer-redhat which should make this a lot easier.

**Comment by sindresorhus** [comment]
@forivall FYI, in [1.3.1](https://github.com/sindresorhus/caprine/releases/tag/v1.3.1), Icon.png was moved from the `media` folder to `static`.

**Comment by sindresorhus** [comment]
Done in https://github.com/sindresorhus/caprine/releases/tag/v2.0.0
