### ISSUE TITLE
Vibrancy mode broken after redesign

### ISSUE THREAD

**Issue by hummuswins** [sindresorhus/caprine#1504]
For some reason, vibrancy has stopped working for me. It would load for about a second then it would get overridden by Messenger it seems. 

https://user-images.githubusercontent.com/22777072/102841928-b1bf1480-43ba-11eb-90cf-783fb11f890c.mov

Caprine Version 2.51.2 (2.51.2)
OS: MacOs Big Sur 11.1

**Comment by jpc632** [comment]
I have had the same issue as of today on Ubuntu 20.04

**Comment by jpuxdev** [comment]
Same!

**Comment by PrimozR** [comment]
Same, the Messenger redesign broke Caprine a bit, in regards to themes and notifications (notifications also don't work for me).

**Comment by dusansimic** [comment]
Dark mode is fixed and merged into master. It will be available in next Caprine update. Vibrancy mode is not fixed yet but it's on our issue list.

We will track vibrancy mode issue here and report any progress. Please don't spam about having the same problem since we already know there is a problem. If you have a working solution or have some information that will help us solving the issue, please post it here. It will help us a lot.

Thanks for the patience 😁.

**Comment by CrazyMacaroon31** [comment]
Hey guys! I made a build with the latest commit.
https://github.com/CrazyMacaroon31/caprineunofficial/releases/tag/tempfix
This build has fixed dark mode.
