### ISSUE TITLE
Dark mode not working. Running latest caprine.

### ISSUE THREAD

**Issue by JGabT** [sindresorhus/caprine#1518]
![image](https://user-images.githubusercontent.com/9552055/103597977-7a18a680-4f3c-11eb-8a25-d471237bb7c9.png)

**Comment by Rozkipz** [comment]
Not sure if this has been updated/changed since I last looked, but you can:
1. Press F12 while focused on the caprine window.
2. Paste `document.querySelector('html').classList.add('__fb-dark-mode')` into the console.
3. Close the console.

And that should enable a decent dark theme.

**Comment by dusansimic** [comment]
This issue is fixed and merged into master. The fix will be available on next update (the one after 2.51.2 since that's the latest one). Regarding the quick fix, @Rozkipz is right. That's how we fixed it basically with minor patches.

**Comment by nmd1** [comment]
Is there a way to open the console from the UI? The F12 keybinding is intercepted by my OS, and there doesn't seem to be an immediately obvious way to open it from the menu bar.

**Comment by dusansimic** [comment]
I think you should be able to open DevTools by right clicking anywhere on the app and clicking 'Inspect Element' menu option. That should then show DevTools window. Then just click on the 'Console' tab and the code from comments.

I'm not sure if this will work since I don't use a Mac but it works on Linux and Windows.

**Comment by JGabT** [comment]
can't you do command+shift+c or command+shift+i
