### ISSUE TITLE
Notifications not working properly.

### ISSUE THREAD

**Issue by mkono87** [sindresorhus/caprine#1521]
Running Manjaro KDE on a few systems. I thought it was maybe just some setting but having issues on all installs. I noticed the taskbar icon does not turn blue when there is a new message and I don't get any pop notifications anymore. I only get sound at the moment.

I also noticed the dark mode toggle doesn't work either.

**Comment by zegkljan** [comment]
Can confirm in GNOME Shell 3.38.2 in Arch.

**Comment by dusansimic** [comment]
Dark mode issue is fixed and is merged into master however it's not available in Caprine yet. It will be available in the next update.

The notification issue is due to Messenger website not showing any notifications on new design. I'm not sure when notifications will be supported since the whole new interface seems unfinished but once Messenger starts supporting notifications again, so will we.
