### ISSUE TITLE
Some features not working

### ISSUE THREAD

**Issue by Sudeep-Sharma0-0** [sindresorhus/caprine#1522]
The dark mode is not working. I made dark mode and then restarted nothing happens.
Also I am not getting notifications. :( 

Caprine 2.51.2
Electron 10.1.5
Linux 5.4.0-60-generic
Locale: en-US

**Comment by jarnalyrkar** [comment]
Same here, windows 10

**Comment by tsbarnes** [comment]
Same, running on Ubuntu 20.10. No notifications, and dark mode doesn't work.

**Comment by dusansimic** [comment]
Dark mode fix is merged into master. It will be available in the next update.

Notifications are not working because messenger website doesn't send notifications anymore. That can't really be fixed by us without a lot of hacking and reverse engineering. Right now we're focusing on what can be fixed and you can track that in [this](https://github.com/sindresorhus/caprine/pull/1514) pr.

**Comment by mzso** [comment]
[**@dusansimic**](https://github.com/dusansimic) commented on [2021. jan. 11. 15:47 CET](https://github.com/sindresorhus/caprine/issues/1522#issuecomment-757998055 "2021-01-11T14:47:25Z - Replied by Github Reply Comments"):
> Notifications are not working because messenger website doesn't send notifications anymore. That can't really be fixed by us without a lot of hacking and reverse engineering. Right now we're focusing on what can be fixed and you can track that in [this](https://github.com/sindresorhus/caprine/pull/1514) pr.

Well that sucks. It's a basic necessity.

**Comment by dusansimic** [comment]
I'll close this now. Once Facebook implements notifications on Messenger website, that will be fixed too.
