### ISSUE TITLE
Tilling window manager won't manage caprine's window

### ISSUE THREAD

**Issue by Lef-F** [sindresorhus/caprine#1523]
Hi,

Thank you for such an amazing open-source implementation! 

I've been using Amethyst as a tilling window manager for a long time on macos and it is the first time I notice a window being unaffected by any tilling window changes I apply. I tried converting caprice to a floating window and back, but still nothing. It just permanently floats as if I have no window manager at all. 

The rest of the windows are managed as expected. I am using other Electron-based projects like vscode and spotify and obey the tilling window changes without any issues. 

Do you have any idea what could be the cause?

One thing I've noticed is that the shadow casted by caprine's window is different (darker) than all other windows.

macos: Big Sur 11.1
caprine version: 2.51.2
amethyst: 0.15.4 (91)

EDIT: Today it's the first time I installed and used caprine. This issue has been happening exactly as documented above for the entire time. I tried relaunching, but not reinstalling.

**Comment by dusansimic** [comment]
Hi @Lef-F! Sorry for the long wait for response. I'm not using a Mac so I personally can't really help you with this. A lot of issues have been broken due to Messenger website redesign including window dragging (which is now fixed) on macOS. Try downloading the latest version of Caprine (v2.52) which has window dragging fixed. Since I can't really help you, I think you would get more help on the Amethyst repo.

In case the update didn't fix anything or the behaviour is somehow changed, please let me know.
