### ISSUE TITLE
in v2.51.2 for Linux the systray icon click doesn't toggle the window

### ISSUE THREAD

**Issue by lashkevi** [sindresorhus/caprine#1529]
In v2.45.0 when I click on the systray icon the message window toggles (appears or disappears) immediately. In v2.51.2 it only opens the menu Toggle/Quit instead, which is highly inconvenient.

OS: Linux OpenSUSE 15.1.
Environment: KDE Plasma 5.12.8 under xorg-x11-7.6_1.

**Comment by dusansimic** [comment]
This is an issue with Electron. Electron uses libappindicator for displaying the tray icon and they don't support click events since I think version 3.0. We cannot fix this in Caprine. There have been several issues reported in the past, one of witch is this one https://github.com/electron/electron/issues/6773. This issue should be reported on the Electron repo.

**Comment by lashkevi** [comment]
That thread is of 2016. But everything worked well at least till November 2020. Why not to continue compiling Caprine with a nonbuggy version of Electron?

**Comment by dusansimic** [comment]
https://github.com/electron/electron/issues/14941 this issue is from 2018 however it's been active so far. The thing about this is that it's not a bug, it's a deliberate change in the way Electron handles tray icon clicks.

Probably the reason tray icon had expected behavior for you so far is that OpenSUSE has only now rolled out some KDE update that has changed the way Electron handles tray icon behavior.

You've suggested we use an older version of Electron in order to maintain the expected tray icon functionality. That is a bad idea since for example Electron v8 which was used in Caprine 2.45 has the expected tray functionality on some DEs and on some it has the current behavior (showing menu when clicked). That would make inconsistent behavior of tray icon across different desktop environments which would be hard to differentiate from a legitimate bug.

Second reason that is a bad idea is that the only version that had consistent expected behavior (showing app when clicked) is Electron v2 which is too far behind current version used Electron v10. Reverting to that version would result in most of the codebase being rewritten and many we would be open to many security holes since that v2 is not receiving security updates anymore.

My recommendation is to file an issue on Electron repo. The best thing that we, Caprine developers, can do is provide consistent behavior across DEs. I know it's an unexpected behavior but the problem is with Electron and we can't fix it without potentially breaking Caprine.

**Comment by dusansimic** [comment]
@nekromoff 
The problem is that tray icon is created by Electron. We use Electron to create a tray icon and the context menu for it (Show and Quit options). Electron uses app indicator to create a tray icon on Linux by default. If app indicator is available/supported by the distro, GtkStatusIcon is used instead. I just want to be clear, this is not something we can chose on Caprine side, everything is handled inside Electron and we just call a function to create a tray icon.

Now the problem is that with app indicator, Electron on click opens/closes the context menu (menu with Show and Quit options) but doesn't emit the `click` event meaning we cannot know when the tray icon is clicked in our code. On GtkStatusIcon, `click` event is emitted so if you're using GtkStatusIcon instead of app indicator, then click on tray icon to show the app will work. Even if it seems like we can get the event when tray icon is clicked, we cannot because the context menu is opened and closed by Electron, not by our code.

The result of everything is that if you're using app indicator, click on tray icon **will not** show the app and if you use GtkStatusIcon, click on tray icon **will** show the app. Most of Linux distros today use app indicator instead of GtkStatusIcon so it is generally a bad idea to still try to use GtkStatusIcon. This issue (lack of click event on app indicator) should not be fixed or worked around here, it should be fixed in Electron.

I hope this helped clarify some things. If there's anything else, let me know.
