### ISSUE TITLE
it s possible

### ISSUE THREAD

**Issue by ViRuS-MaN** [sindresorhus/caprine#1537]
i just found you programme and i ask to you it s possible to remove the picture and info in the right windows ans only show the people are connected in the facebook

---

Caprine 2.52.0
Electron 10.1.5
win32 10.0.17763
Locale: fr

**Comment by dusansimic** [comment]
I'm not sure I understood what you mean. Do you mean can we remove the profile picture and other options from the right sidebar (right from the messages) and just show if user is active (green dot)?

**Comment by ViRuS-MaN** [comment]
yes it s at that i think

Le mer. 27 janv. 2021 à 20:40, Dušan Simić <notifications@github.com> a
écrit :

**Comment by dusansimic** [comment]
It is possible, however we don't plan on adding that since there are a lot of tools and options in the right sidebar which are useful and sometimes necessary. What I would recommend now is adding custom styles which would do what you wish. You can do that by clicking File > Caprine Settings > Advanced options > Custom styles. A file should open and you should be able to write custom CSS that will do the thing you want. I hope this helps.

I will close this issue now since we don't plan on adding this to Caprine.

**Comment by ViRuS-MaN** [comment]
it's a pity, because unfortunately I'm not good at CCS, so I couldn't
include that, it would have been good to have an option for those two
things there.

Le jeu. 28 janv. 2021 à 15:18, Dušan Simić <notifications@github.com> a
écrit :
