### ISSUE TITLE
Dark mode do not work

### ISSUE THREAD

**Issue by IpyZ** [sindresorhus/caprine#1538]
Hi!
Dark mode doesn't work form me. I think this may be fault of strange messenger update, that deletes some features for people living in European Union (or Poland only, but still update deletes some features).
On messenger official site dark theme work correctly.

**Comment by dusansimic** [comment]
Hello!

The messenger update is not limited just to Europe but to other countries too. The new update has changed the hole design of the website and thus has broken many features that Caprine added to the website.

Please check that you have the latest version (2.52) in which we fixed dark mode issue alongside some other issues. Keep in mind that not everything is fixed so you might run into some issues. One issue we know about and we're working on regarding dark mode is that it's not turned on automatically on start of the app even if you've enabled it in the menu bar. To solve this, for now you can just turn off and turn back on the dark mode in the menu bar which will enable it.

There are some UI patches that we're working on for dark mode but this will solve most of your issues. Please let me know if you've solved it or there is some more issues regarding dark mode.

**Comment by LogMoss** [comment]
Dark mode stopped working recently on Arch, I'm running the newest 2.52 version and checking dark mode box on/off adds/removes `__fb-dark-mode` class on a `html` tag.

**Comment by LogMoss** [comment]
I guess the last release broke it, I downgraded and dark mode works again

**Comment by dusansimic** [comment]
@LogMoss I'm not sure how you downgraded and dark mode works. Dark mode was fixed in the latest version (v2.52) however there is an issue, when Caprine starts dark mode is not set automatically and you have to disable it and enable it again. That issue is reported here #1538. To clarify, dark mode works (on version v2.52) but it is not enabled automatically on start.

**Comment by LogMoss** [comment]
Heres another person whose dark mode stopped working recently: https://github.com/sindresorhus/caprine/issues/1525#issuecomment-770222431
My guess is that your recent update maybe fixed it on Debian but broke it on arch distros, because my dark mode has worked fine for months but few days ago it was white when I opened caprine and switching dark mode on and off didn't make any difference.
I used Pacman's cache to downgrade to some 2.5 version.

**Comment by dusansimic** [comment]
The last update has added support for dark mode. I'm running an Arch based distro and it works for me. However, as I have already said in my previous commend and as you have linked in your comment, dark mode is not enabled when application is started. To enable it you have to turn dark mode off and on again. This will work ONLY on version (v2.52).

The issue about dark mode not being enabled by default is already reported. The issue about dark mode not working is fixed.

>because my dark mode has worked fine for months but few days ago it was white when I opened caprine and switching dark mode on and off didn't make any difference

What you're talking about here is Messenger website being updated. The new design has broken many Caprine features which we are now slowly fixing. You couldn't enable dark mode with switching it off and on again because that is possible only in the latest version (v2.52).

>I used Pacman's cache to downgrade to some 2.5 version.

Please upgrade to 2.52.

I'm sorry if there was some misunderstanding. I hope this helps.

**Comment by LogMoss** [comment]
Well thats weird, on 2.52 changing dark mode on and off didn't work for me and after downgrade to 2.51 something it worked out of the box like it was working before.

**Comment by iverik-no** [comment]
@LogMoss I've also had issues with Dark Mode. Today I installed 2.52, and while Dark Mode was switched on in the settings from before, I tried setting it to Follow Systeam Appearance instead (where I have DM enabled). That made it swtich to Dark Mode. Then I could set it to the Dark Mode setting too and have it keep DM on :) Tried switching around the modes of the previous versions without luck (when it disappeared all of a sudden), but now it finally worked.

This was on my Macbook. Haven't tested on my Linux desktop yet.

**Comment by Skoti** [comment]
I was running Caprine version 2.51.2 in dark mode without any issues. After upgrading to 2.52 the dark mode is gone.
Turning it on/off only changes the Caprine window border (screenshots below) - a thin black border around white Caprine window. Toggling "Follow system appearance" (I am using dark mode) also does not have any effect. The same goes for relaunching Caprine after changes.
![caprine_dark_mode_disabled](https://user-images.githubusercontent.com/1700160/107762991-2749c000-6d2e-11eb-8c4b-99d8cdccd620.png)
![caprine_dark_mode_enabled](https://user-images.githubusercontent.com/1700160/107763002-2a44b080-6d2e-11eb-9d08-f9d5272188cc.png)

**Comment by vuon9** [comment]
The dark mode is gone when download the app from brew (v 2.52.0), but still working if I install from the source by npm...

**Comment by Skoti** [comment]
> The dark mode is gone when download the app from brew (v 2.52.0), but still working if I install from the source by npm...

Yeah I'm using brew-installed Caprine as well. Is this still Caprine issue or rather something that brew does?

**Comment by Knogobert** [comment]
v2.52.0 works flawlessly in dark mode for me after running `brew reinstall caprine`

**Comment by dusansimic** [comment]
@Skoti this is a Caprine issue. I'm working on a fix for this (#1569) and once it's pulled and a new version is released, you'll get the fix.
