### ISSUE TITLE
Toggle unread threads?

### ISSUE THREAD

**Issue by mattnoir** [sindresorhus/caprine#1550]
Hi
I know there are many things broken now due to redesign, however this feature I did not see in the checklist of features to be fixed and I did not find it anywhere else.
So I want to ask if this feature is no longer supported by the redesign. If that is the case, that really sucks, as I have several threads unread for a long time and sometimes I actually reply to them :/

**Comment by dusansimic** [comment]
Hi @mattnoir! It seems that indeed this feature is not supported by the redesign. It might be implemented later however we don't know anything for sure. Some features that now exist in the new design were not there when it first came out, like search in conversation, so we don't know for sure if it's not going to be implemented some time later. Unfortunately, we can't implement anything that will work good since we would have to go through all the messages. I'll close this since there's nothing we can do about it for now. If that feature gets implemented by Messenger website, please feel free to ping this issue.
