### ISSUE TITLE
several issues on big sur M1

### ISSUE THREAD

**Issue by mardulas** [sindresorhus/caprine#1551]
Big Sur on Apple M1 MBP
Always starts as light interface regardless of the setting (dark or follow).
Always opens "Messenger Preferences" on startup.
View - Sidebar options doesn't do anything.
"Hide names and avatars" doesn't do anything.
Insert GIF (cmd+G) or Insert Sticker (cmd + S) doesn't do anything. 

That's it for now.
---

Caprine 2.52.0
Electron 10.1.5
darwin 20.3.0
Locale: en-GB

**Comment by dusansimic** [comment]
Hi! Some of these issues are already know and being worked on.

>Always starts as light interface regardless of the setting (dark or follow).

#1525 

>Always opens "Messenger Preferences" on startup.

#1547 

>View - Sidebar options doesn't do anything.

I'll open this as a separate issue.

>"Hide names and avatars" doesn't do anything.

#1555 

>Insert GIF (cmd+G) or Insert Sticker (cmd + S) doesn't do anything.

Can you open this as a separate issue with some more info about what is going on?
 * Do the buttons in message box work?
 * Do the menu bar options work?
 * Do the shortcuts work?
 * Do you have menu with more actions open? Here is an image of that menu. Do the options work when that menu is closed?
![image](https://user-images.githubusercontent.com/12685466/107848806-a99db700-6df6-11eb-86d4-a3436ffd9210.png)

Thanks for reporting all of this but in order to keep things organized and to know clearly what issues are still reamining I'll close this and separate issues should be opened. The one that needs more info is the last one (Insert GIF/Sticker shortcut) so if it's not too much trouble, I'd ask you to open that one 😁.
