### ISSUE TITLE
latest.yml hash for .exe release does not match on my machine

### ISSUE THREAD

**Issue by v4k0nd** [sindresorhus/caprine#1554]
According to the latest.yml the hash of the newest release for Windows (.exe) starts as 9GKiEbubaPc62vYCmCy8cYt... and on my machine it did not match.
I checked two ways on my win 10 (ver. 20H2 build 19042.746):
`powershell> Get-FileHash .\Caprine-Setup-2.52.0.exe -Algorithm SHA512`

`cmd> certutil -hashfile Caprine-Setup-2.52.0.exe SHA512`

and they both resulted in a hash starting as 58a1bcf1f7af889bbfd6222e...
Could somebody else check it? Did I check it in a wrong way?

**Comment by v4k0nd** [comment]
Going back 3 releases it still does not match (it is probably just my machine or my way of checking was wrong then)

**Comment by dusansimic** [comment]
Hi! You're right, the hash is not correct. I've checked hashes for all platforms (Windows, macOS and Linux) and they don't match. I'm not sure what is the problem since those hashes in yaml file are generated by Electron Builder. I'll leave this open until we figure out what is going on here.

**Comment by v4k0nd** [comment]
Ah that's a relief on my end then, I was searching everywhere how could I be getting the wrong hashes. Thank you for the quick response!

**Comment by v4k0nd** [comment]
I think I found something, there is a nearly two year old issue/answer in [electron-builder](https://github.com/electron-userland/electron-builder/issues/3913#issuecomment-504698845).
Under the mentioned issues, I found [this](https://github.com/electron-userland/electron-builder/issues/3119#issuecomment-405097164), where it says that electron-builder wont just calculate the SHA512 and output it in ascii, but after calculating the SHA512, it takes the binary and converts it to base64. I should have noticed that it is not just normal ascii since because the sha512 has a `==` at the end, which indicates padding for the encoding, usually.

However this does not answer me how to check it "manually" (only cmd / powershell / bash commands). 

I did find something for bash in [this issue](https://github.com/th-ch/youtube-music/issues/69#issuecomment-735396905) but it did not calculate the correct hash, nor any combination from the mentioned stackexchange link.

If I manage to find an answer I will try to keep this issue updated.

**Comment by dusansimic** [comment]
@v4k0nd thanks for the comment! I've tested it out any you're right, the hash is still incorrect. I've however tried building Caprine on my machine and the hashes of the AppImage package and hash in yaml file are the same. Also, I've checked for hashes of YouTube Music packages (linked in your comment) and [Hyper Terminal](https://github.com/vercel/hyper). They both seem to have correct hashes in yaml files for their packages. That points to the difference in the build process.

I'm not completely sure if Hyper is building each package on it's target OS (Linux on Linux, Windows on Windows, macOS on macOS) but they seem to have included different operating systems in the build process ([here](https://github.com/vercel/hyper/blob/faaad901fe89317abd415d1614862564b303ba76/.github/workflows/nodejs.yml)). The same goes with YouTube Music while there is very clear that packages are being built on their target OS ([here](https://github.com/th-ch/youtube-music/blob/5a1358b3100c9de776b044494d940ee2a7e0146d/.github/workflows/build.yml)). Caprine is being built on macOS for all platforms since that is possible (macOS can be used as a universal build platform for all three operating systems) and that might be the reason for this issue ([here](https://github.com/sindresorhus/caprine/blob/0e5175bc1983249af0e99105079bc6109470d958/.github/workflows/main.yml)).

**I cannot confirm this** since I don't have a Mac to test it out so I don't want to point finger at it yet, however this seems quite likely that it's the reason. A way that we could test this out is to create a build process for Caprine which would use three operating systems instead of just one. If the hashes in yaml files match hashes of the packages, it would be the solution to this problem.

This means that there would need to be some change to the build process so it might take same time to even test if it works. Right now most of the focus is on fixing issues caused by new messenger design so I won't be able to handle this.

A good starting place would be splitting `dist` script in `package.json` into three separate scripts for each OS. Then the build process would need to be split into three separate build steps for each OS. Build yaml from YouTube Music would be a good inspiration for this.
