### ISSUE TITLE
screen stuck issue

### ISSUE THREAD

**Issue by nnabicse** [sindresorhus/caprine#1582]
[<!--](url
![Error](https://user-images.githubusercontent.com/69366614/110794314-d0d59000-829f-11eb-9e7c-b6e6756193c9.png)
) 

After installing caprine, First one or two days was ok! After that when i open caprine it shows me black screen and the black portion doesn't works.

---

Caprine 2.52.1
Electron 10.1.5
linux 5.4.0-66-generic
Locale: en-US

**Comment by dusansimic** [comment]
What was the installation method? Snap, DEB or AppImage? What distro are you using?

**Comment by nurunnabi-cse** [comment]
> What was the installation method? Snap, DEB or AppImage? What distro are you using?

Snap installation.
Linux Mint 20.10

**Comment by holdenout** [comment]
I have the same issue when waking from suspend, whether the window was open or not. Restarting Caprine fixes it, but it still happens on each suspend.
Snap Installation, Pop!_OS 20.10

**Comment by phusen** [comment]
I have the same problem on Ubuntu 20.04 with caprine 2.52.0 installed as a deb. I think it's related to this issue: https://askubuntu.com/questions/1273399/problems-with-chrome-browser-after-suspending-the-computer-on-ubuntu-20-04

This was later fixed in Chrome, and I seem to recall it was also fixed in Electron (at least the problem went away in other Electron-based apps), but I can't find the source of that just now. But maybe this would be a question of updating the version of Electron used by Caprine?

**Comment by phusen** [comment]
Updating my earlier comments: It appears there is a fix/workaround in Chromium 87/88 (not entirely clear to me which one from the thread): https://bugs.chromium.org/p/chromium/issues/detail?id=1113040

So perhaps an upgrade to Electron 11 (using Chromium 87) or 12 (using Chromium 89) would fix this issue.
https://www.electronjs.org/releases/stable

**Comment by dusansimic** [comment]
> So perhaps an upgrade to Electron 11 (using Chromium 87) or 12 (using Chromium 89) would fix this issue.

Dependency upgrade is in plan so this should be fixed once Electron is upgraded. Currently we need to work on removing use of some features that are deprecated in Electron 12.
