### ISSUE TITLE
Request for Flatpak and/or rpm package.

### ISSUE THREAD

**Issue by RDKRACZ** [sindresorhus/caprine#1594]
Hi, I use Mageia 8 as my daily driver and would like to use Caprine like I was using it on Ubuntu-based distros, however I can't because there is no package for fedora like distributions or flatpak one. I won't be using bad snap packages.

**Comment by dusansimic** [comment]
Hi @RDKRACZ! As maintainer has already stated in several other issues (#1411 and #577) there are no plans for adding any new package formats for Linux. Primarily the reason is that we would need to maintain and fix problems as they arise in every package format and that would get increasingly harder as we add new formats.

A solution would be to either make third party unofficial builds or to ask distros official repository maintainers to create packages for their distro. There is already an issue open regarding rpm packages (#1458). As for Flatpak, I have some questions about it that are still left unanswered https://github.com/sindresorhus/caprine/issues/577#issuecomment-732272580.

I'll close this since there are already issues open that are tracking the same thing.
