### ISSUE TITLE
fb story click > This page isn't available > must restart caprine

### ISSUE THREAD

**Issue by igor-werry** [sindresorhus/caprine#1601]
Hi there,
thanks for an amazing app! Love it!
There's an odd thing happening when in the app 2.52.2 I click on the story link. For example someone leaves a reply to fb my story and I click on that story in the app, I get the info screen and then no way to return to the chat.
![2021-04-06 02_20_48-Messenger](https://user-images.githubusercontent.com/51317962/113641909-d8aa0980-967e-11eb-9f7e-9142632bb10d.png)
![2021-04-06 02_18_35-Messenger _ Page Not Found](https://user-images.githubusercontent.com/51317962/113641916-dc3d9080-967e-11eb-8c6a-289445d3e3cb.png)

Thank you so much,

**Comment by dusansimic** [comment]
Sorry for the late response. Try copying the link and opening it in the web browser. This issue seems to be with the link rather than Caprine. If the same issue happens in the web browser then it's completely unrelated to the app an could be just that Facebook has a buggy link, the story has expired or something else all together.
