### ISSUE TITLE
Can you include a list of features that are still broken when you release a new version?

### ISSUE THREAD

**Issue by Amandaville** [sindresorhus/caprine#1634]
I keep getting email notifications when a new version of Caprine is released, only to spend a bunch of time on it and then find out that "Block Seen Indicator" is still not working.  I have no use for Caprine without "Block Seen Indicator".  Can you include a list of features that are still broken when you release a new version?  That would really help some of us avoid wasting time on crippled releases.

**Comment by RDKRACZ** [comment]
>crippled releases.

Then don't use caprine / contribute to fix this. "If anyone is interested in helping out or at least researching a bit more in depth this issue and how Messenger might be handling those "privacy" features (sending seen reports, typing reports and block delivery receipts), we'll be very thankful. Right now because of the scale of the update of Messenger, we are basically building every feature from scratch and it might take some time until we get back on our feet."

>Can you include a list of features that are still broken when you release a new version

If an issue is not closed that probably means it's not fixed you know?

>only to spend a bunch of time on it and then find out that "Block Seen Indicator" is still not working

Soo like 30 seconds to download with a bad connection, another 30 to install. You wasted more time on writing this "issue".

**Comment by dusansimic** [comment]
@Amandaville it's a good suggestion but the main problem with that is we know what definitely doesn't work (for example privacy features) but we've learned that Facebook has a habit of pushing different versions of frontend for different users and it's not uncommon for some users to experience issues that other users don't and vice versa. That also creates a problem if I or some other contributor don't have access to that version of frontend, we can't really fix the issue blindly or it's really hard and time consuming. I will think of a good way to keep the list of "todo" features that we didn't fix yet but it may not always reflect to all users.

Regarding the fixing of privacy features, I've started to work on it already and thanks to user contributions and research in #1503 I know how to at least try to do it but I'm wrestling with TypeScript a bit. I'll make a pr and if anyone is interested, they could try to help out but for now it's a work in progress.

Thanks for the issue!
