### ISSUE TITLE
Caprine installer hangs in Windows 10 build 21376.1

### ISSUE THREAD

**Issue by nityesha** [sindresorhus/caprine#1636]
Windows Explorer window hangs on execution of the Caprine-Setup-2.53.0.exe.

**Comment by dusansimic** [comment]
Hi @nityesha. What build of Windows do you have (32bit or 64bit)? Did restarting your computer help? Did that every happen before? Is there any error message displayed?

**Comment by mquevill** [comment]
It looks like that build is currently on the Dev Channel of the Windows Insider Preview. Since it's the most unstable of the Insider Preview channels (Dev, Beta, Release Preview), there may be existing bugs/issues in the build. Though, it might still be useful to try to track down the source of the hang.
