### ISSUE TITLE
Add a better emoji picker

### ISSUE THREAD

**Issue by Samuel-B-D** [sindresorhus/caprine#1639]
Messenger's own emoji picker is completely broken. It takes like 1-2sec. to open, but that's EVERY TIMES, not just the first time.

Since it's so broken and facebook doesn't seems to want to fix it, why not just add a better one in caprine?

**Comment by dusansimic** [comment]
I agree that Messenger emoji picker is a bit buggy and slow but we don't plan on adding any new features. I would instead recommend using integrated emoji picker in the operating system. On [macOS](https://www.macrumors.com/how-to/use-emoji-on-mac/) it seems you can open it with `Command+Control+Space`, on [Windows](https://www.howtogeek.com/351344/how-to-use-windows-10%E2%80%99s-new-emoji-picker-in-any-app/) use `Win+.` or `Win+;` and on Linux you can install an emoji picker extension or some other additional program for picking emojis. On Gnome desktop environment (Linux) I use `gnome-shell-extension-emoji-selector` extension.

I'll close this now since we don't plan on adding a custom selector.
