### ISSUE TITLE
Debian package depends on libappindicator3-1

### ISSUE THREAD

**Issue by jaubin** [sindresorhus/caprine#1658]
Hi,

It is not possible to install Caprine on latest Debian (bullseye) since package libappindicator3 has been removed. Use instead package libayatana-indicator, see : https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895038 . It will also impact *buntus sooner or later.

See signal-desktop for examples.

BTW do you have a Debian repo for Caprine packages ?

Thanks

**Comment by dusansimic** [comment]
Hi @jaubin!

> Use instead package libayatana-indicator

The thing is we don't require libappindicator ourselves. Electron requires it as a dependency and since we use Electron to make Caprine, you need libappindicator. This issue should be reported on Electron repo because it's their issue.

> See signal-desktop for examples.

From the issues I've looked up on signal-desktop repo ([here](https://github.com/signalapp/Signal-Desktop/issues/4866) and [here](https://github.com/signalapp/Signal-Desktop/issues/4761)) they didn't fix the issue but rather discussed how you can install libappindicator on Debian 11.

> BTW do you have a Debian repo for Caprine packages ?

Not at this moment, but I'm working on making 3rd party repos (not supported by the maintainer) and once I've created them you would be able to use them for installing and getting updates of Caprine.

I would recommend using AppImage package in the meantime for Debain 11. It's statically linked version which means that it should work because it bundles all required libraries in the package itself.

I'll close this issue since it's an Electron issue and the repos issue is already reported.

**Comment by jaubin** [comment]
The only thing I know for sure is that signal-desktop does not require anymore libappindicator as a dependency. Maybe just put the dependency in recommends would be sufficient
