### ISSUE TITLE
@Contact and Like are no longer functioning

### ISSUE THREAD

**Issue by chardric** [sindresorhus/caprine#1670]
The @contact> to mention a person/friend is no longer functional, and the Like when you press long doesn't get bigger. 

---

Caprine 2.53.0
Electron 10.1.5
linux 5.4.0-80-generic
Locale: en-US

**Comment by mquevill** [comment]
The @<contact> seems to work for me. If you have Facebook set to a different language, it may have had issues creating the popup to select your contact. This should be fixed in the next released version (as commits to fix it are already in the `main` branch).

It appears that holding down on the "Like" button (or whatever the conversation's default emoji is) no longer works on the normal browser-based website [Messenger.com](https://www.messenger.com/). Unfortunately, there are differences between the mobile app and the desktop site (e.g. reacting with any emoji).

**Comment by mquevill** [comment]
Can you check if tagging someone (@<contact>) works in the newer version? I believe that issue should be fixed with the new release (2.54.0).

**Comment by dusansimic** [comment]
Solved
