### ISSUE TITLE
Dark Mode text stuck as black

### ISSUE THREAD

**Issue by raza453** [sindresorhus/caprine#1672]
![image](https://user-images.githubusercontent.com/88105983/127366477-0d899696-8377-42ee-ad03-82851f8d1ece.png)

Not sure why this is happening, on Windows 10. All text's sent to me are in black while using dark mode.

**Comment by tobywrites** [comment]
Also happening on Mac. Any tips on how to change back to white text?

**Comment by karelo911** [comment]
Same issue both on my mac and windows laptops

**Comment by matthewstrasiotto** [comment]
yeah this started happening for me, idk if anything else has broken. 
IIRC this usually happens when messenger.com's markup / CSS changes so the caprine selectors break. 

Sometimes features like disabled read receipts etc also break

**Comment by matthewstrasiotto** [comment]
Until devs fix it, I'll try writing some custom CSS for it - Looks like the message elements have a class of 
`n3t5jt4f` , and "your" messages have a class of `qsbzbi57`, whilst "theirs" have `pbevjfx6`

![image](https://user-images.githubusercontent.com/39424834/128678165-5e4ae955-bc46-40ef-8faa-cb91e826be2f.png)

**Comment by matthewstrasiotto** [comment]
Here - put this in your custom styles:

```css
html.dark-mode .n3t5jt4f.pbevjfx6 {
	color:  white;
        /* Or you can use 
        color: var(--base-ninety);
        */
}
```

**Comment by karelo911** [comment]
> @tobywrites @karelo911 @raza453
> 
> Here - put this in your custom styles:
> 
> ```css
> html.dark-mode .n3t5jt4f.pbevjfx6 {
> 	color:  white;
>         /* Or you can use 
>         color: var(--base-ninety);
>         */
> }
> ```
> 
> Edit them like this
> 
> ![image](https://user-images.githubusercontent.com/39424834/128679900-fc8cb5aa-b93a-4bd9-8cdd-ad6c82ad595f.png)
> 
> Save the css file & reload caprine with Ctrl/Command + R

Works perfectly. Thank you very much for this workaround!

**Comment by mquevill** [comment]
The classes that @matthewstrasiotto identified are not present in my Messenger interface, so perhaps they are rolling out _yet another_ new interface? On Windows and Linux, I have not been able to replicate the black text or even query those classes. The slow rollout of new interfaces with no way to specify which one you get makes development difficult.

Could you show us what the classes of the main HTML element and the body are? Shown below is what I see when I open Developers Tools:

```html
<html id="facebook" class="_9dls" lang="en" dir="ltr">
  <head>...</head>
  <body class="_6s5d _71pn _-kb vsc-initialized">
    ...
```

----

The text color is not explicitly set when dark mode is activated. Simply adding a `__fb-dark-mode` class to the main body should toggle most elements to Messenger's preset dark mode settings. There are a few elements that Caprine has to clean up since it's not quite a fully functioning setting in Messenger.

In the current "new" interface, the text sent by you is colored with `--always-white`, while the text received by you is colored with `--primary-text`. If the dark mode changes the primary-text variable, maybe we can add this color to the CSS applied by Caprine for these new classes?

**Comment by tobywrites** [comment]
> @tobywrites @karelo911 @raza453
> 
> Here - put this in your custom styles:
> 
> ```css
> html.dark-mode .n3t5jt4f.pbevjfx6 {
> 	color:  white;
>         /* Or you can use 
>         color: var(--base-ninety);
>         */
> }
> ```
> 
> Edit them like this
> 
> ![image](https://user-images.githubusercontent.com/39424834/128679900-fc8cb5aa-b93a-4bd9-8cdd-ad6c82ad595f.png)
> 
> Save the css file & reload caprine with Ctrl/Command + R

Worked perfectly, thank you very much!

**Comment by avidianity** [comment]
I have the same issue in Manjaro.

**Comment by dusansimic** [comment]
@mquevill, from some other issue (#1588) I've found out that Facebook is still updating the old design which means that the css for old design might not work as expected. I'm not sure weather this is the old or new design but we should keep in mind that there has been some bugs with Facebooks `__fb-dark-mode` class (I don't have any evidence at hand but I've experienced some text color related issues in the past).

A good idea would be to change the default contents of `custom.css` file which is set in `click()` function for Custom Styles menu option depending on weather it's new design or old.

The thing that still confuses me is how this issue is present on some new designs (if we take that as a fact) and not on others if we expect that Facebook is not rolling out two new designs. A good idea would be to create a menu option (similar to About Caprine option) which would show a window with information related to website design useful to developers (whether it's new or old design, locale, weather some specific classes exist, dark/light mode css from fabebook...), it might help us understand what are users having displayed as a website and weather it's a bug in Caprine or the website. It would also make it easier for developers to gather such information by just telling users to click on that option and paste the information in an issue or pastebin rather than teaching them how to open dev tools since that's what we've been doing in the past.

**Comment by dusansimic** [comment]
It seems like the issue is with the div element wrapping the text message. It contains a class `__fb-light-mode` whose  `--primary-text` is `#050505`.

![image](https://user-images.githubusercontent.com/12685466/129183543-35465664-d2fd-46f3-8974-1f74bf04bb98.png)

That turns the text color in the message box black even if dark mode is enabled globally.

I've managed to fix it by adding the following css to `custom.css` file:

```css
.__fb-dark-mode .__fb-light-mode {
	--primary-text: #e4e6eb;
}
```

It sets the `--primary-text` value to one from dark mode only if there is an element with class `__fb-dark-mode` that contains and element with class `__fb-light-mode` which is our case. I'll make a quick pr to add this workaround since it seems to be a problem on Facebooks side until it's fixed.
