### ISSUE TITLE
Dark mode has black text on gray backgroud

### ISSUE THREAD

**Issue by Mukhilm** [sindresorhus/caprine#1686]
The dark mode in Caprine used to have white text when in dark mode but it has now switched to the same black text used in light mode making it very hard to read. I've tried a clean reinstalling with purge to remove all configuration files but the issue still appears. I'm on ubuntu 20.04 running the latest snap package and have also tried the debian direct download.

![image](https://user-images.githubusercontent.com/22032143/129840697-a48c08aa-22e3-40cf-8453-ba2e797b12f4.png)

**Comment by RDKRACZ** [comment]
Looks like a duplicate od #1672.

**Comment by dusansimic** [comment]
@Mukhilm this was fixed in #1683 and the fix is available in the latest version. Keep in mind that due to wrong setup of automatic deployment system, snap packages weren't updated for the last 3 versions. Once fixed they will be available. Installing the deb package should've fixed the issue. Are you completely sure you've downloaded the latest deb version while having the snap version removed (at this moment that is v2.54.1)?

**Comment by Mukhilm** [comment]
Ah yes removing the snap package and installing the deb fixed the issue
