### ISSUE TITLE
[Flatpak] the toolbar doesn't respect dark theme setting.

### ISSUE THREAD

**Issue by RDKRACZ** [sindresorhus/caprine#1690]
Flatpak on the left, deb on the right.
![Screenshot from 2021-08-23 12-10-16](https://user-images.githubusercontent.com/43277609/130430460-6d5476d7-53d8-4888-8e1e-442ae8896b46.png)
Yes, I restarted flatpak Caprine after enabling the dark mode.

**Comment by dusansimic** [comment]
Install `org.gtk.Gtk3theme.Adwaita-dark` flatpak from flathub.

**Comment by RDKRACZ** [comment]
`Skipping: org.gtk.Gtk3theme.Adwaita-dark/x86_64/3.22 is already installed`

**Comment by dusansimic** [comment]
Did you completely quit Caprine and start it again? You can do so by going to `File` -> `Quit` or pressing <kbd>Ctrl</kbd> + <kbd>Q</kbd>.

**Comment by dusansimic** [comment]
I've just checked on a Live ISO and it doesn't seem to work. You should install the Gtk3theme flatpak which matches the system theme you use (it can be found in system settings under themes). After I installed the required flatpak (`org.gtk.Gtk3theme.Mint-Y-Dark` in my case) I still couldn't get it to work so I'll reopen this. I'm not sure why it's not working since it's working for me on Gnome 40 with Adwaita Dark theme. I'll try to find out what's wrong but I can't make any promises.

**Comment by dusansimic** [comment]
@RDKRACZ after installing Mint and trying it out again, I've managed to fix it. As I said in my previous comment, you'll just need to install the correct flatpak for the theme you use. Let me know if it works.

**Comment by RDKRACZ** [comment]
![Screenshot from 2021-08-23 15-23-28](https://user-images.githubusercontent.com/43277609/130454853-203ba9e0-095f-4e2f-a38b-8539740ce8ea.png)
Ok, but which one of these themes I should install as a flatpak?
Also, seems like some of them are not available as a flatpak.

**Comment by dusansimic** [comment]
> Ok, but which one of these themes I should install as a flatpak?

I'm going to guess that it's the window borders theme you need to install. I don't use Cinnamon so I don't really know which one should be installed exactly.

> Also, seems like some of them are not available as a flatpak.

That does tend to be the case with flatpak. AFAIK you can only theme the apps with themes available on flathub. There might be another way but it's a hacky way. I've installed the `org.gtk.Gtk3themes.Mint-Y-Dark` package and used the `Mint-Y-Dark` theme for everything in that settings menu except for mouse pointer theme.

Since this is a theming issue specific to Cinnamon and your distro, I think you'll get much more help on your distro forums and Cinnamon forums or other communication and help channels.

**Comment by dusansimic** [comment]
Sorry for pinging this issue again. I had a little bit of free time and made a flatpak manifest for the theme that's missing from flathub (CBlack). You can find it [here][manifest]. All you need to do is build it. You can find out how in the [flatpak docs][docs] if you're adventurous 😁. I how it helps and let me know if it works 😊.

[manifest]:https://github.com/dusansimic/flatpaks/tree/main/org.gtk.Gtk3theme.CBlack
[docs]:https://docs.flatpak.org/en/latest/building-introduction.html#flatpak-builder
