### ISSUE TITLE
Black text in Dark Mode

### ISSUE THREAD

**Issue by huoi** [sindresorhus/caprine#1704]
Dark mode is working fine except for chat messages which are displayed in black text.

![image](https://user-images.githubusercontent.com/59074303/132603892-bc868980-bce2-4ef2-a5bd-5d1c29647087.png)

**Comment by wulfalpha** [comment]
i'm kinda jealous dark mode is not working for me at all. Did you do anything special?

**Comment by huoi** [comment]
No I just turned on dark mode in the view menu.

**Comment by wulfalpha** [comment]
shoot. What version of the app are you on? maybe i can find a different version that works.

**Comment by huoi** [comment]
I don't really know how to check the version. I just got it from `sudo snap install caprine`.

**Comment by wulfalpha** [comment]
That's ok man. That helps that you got it from snap. the version I got was from the Arch User Repository so I'll try the snap one next and see if it works better. Thanks man

**Comment by wulfalpha** [comment]
yep I installed the snap version and got the same thing on dark mode. dark text in dark mode. Interesting.

**Comment by mquevill** [comment]
That should have been fixed (at least with a workaround) in v2.54.1. To check your version, go to Help > About Caprine. If that doesn't work, try to go to Help > Report an Issue… where it should open a new GitHub issue that has additional debug information and versions.

The [Snapcraft release](https://snapcraft.io/caprine) is a few versions behind and currently on 2.52.4, so it should be fixed in more updated versions. (See https://github.com/sindresorhus/caprine/issues/1686#issuecomment-900960867 for more details.)

**Comment by huoi** [comment]
Yes I did what you said and It says I'm on 2.52.4.

**Comment by chao813** [comment]
@huoi I had the same issue, solved it by downloading version v2.54.1.

**Comment by huoi** [comment]
Yes I also solved it by downloading and installing the .deb version.
