### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by PreachJohn** [sindresorhus/caprine#1718]
Hide Sidebar does not work at all.

---

Caprine 2.54.1
Electron 10.1.5
win32 6.1.7601
Locale: en-US

**Comment by dmieszczanin** [comment]
Found workaround, just add this line to Custom Styles
`.sidebar-hidden div[role=navigation] {
	display: none;
}`

**Comment by noto-rious** [comment]
> 

Thanks, that seems to work for hiding, but literally none of the other side bar options work for me either. Do you have a workaround for wide side bar?

**Comment by dmieszczanin** [comment]
A quick solution for narrow sidebar
`
.sidebar-force-narrow div[role=navigation] {
	width: 80px;
}`

Getting the wide one to work is a little bit more tricky because the chat text is disappearing from DOM when window gets too narrow.
![image](https://user-images.githubusercontent.com/62097130/146647919-2bd9ee2d-b098-44bb-aca5-d43bff4d9706.png)

I don't think it can be resolved by adding custom styles.
However if you want to try something yourself the CSS selector for wide sidebar is 
`.sidebar-force-wide div[role=navigation] {
	width: 360px;
}`

**Comment by noto-rious** [comment]
> A quick solution for narrow sidebar ` .sidebar-force-narrow div[role=navigation] { width: 80px; }`
> 
> Getting the wide one to work is a little bit more tricky because the chat text is disappearing from DOM when window gets too narrow. ![image](https://user-images.githubusercontent.com/62097130/146647919-2bd9ee2d-b098-44bb-aca5-d43bff4d9706.png)
> 
> I don't think it can be resolved by adding custom styles. However if you want to try something yourself the CSS selector for wide sidebar is `.sidebar-force-wide div[role=navigation] { width: 360px; }`

Ah, thanks for sharing anyways.

**Comment by lefterisgar** [comment]
Closing, as it will be fixed in the next release.
