### ISSUE TITLE
Marketplace is not on Caprine? Messenger from FB has it.

### ISSUE THREAD

**Issue by stamatgeorge** [sindresorhus/caprine#1776]
Marketplace is not on Caprine? The messenger from Facebook now has it.

<img width="207" alt="Screen Shot 2021-12-23 at 4 04 49 PM" src="https://user-images.githubusercontent.com/22395087/147420213-027803a1-8361-4dd5-9a99-3de500cd611b.png">

**Comment by dusansimic** [comment]
If by Messenger from FB you mean the Facebooks Messenger app, that's different from Caprine. You should check weather [messenger.com](https://messenger.com) website has Marketplace since Caprine is just a wrapper around that website. What the website has, that's what Caprine will have, if there is something missing, then Caprine won't have it.

Since those are two different ways to use messenger (Facebooks app and the website which is used by Caprine), it's expected that there are different features implemented.

**Comment by stamatgeorge** [comment]
I was suggesting that Caprine should add “Marketplace" as Facebook did with its Messenger for Mac 134.0.0.14.118..

I checked www.messenger.co and "Marketplace" is not there which is weird. Isn’t it the same platform? Am I missing something? lol

<img width="218" alt="Screen Shot 2021-12-26 at 7 47 19 PM" src="https://user-images.githubusercontent.com/22395087/147424146-0c3b7790-b6a7-40a1-a5de-d01e27da94f5.png">

**Comment by frozenpandaman** [comment]
>I was suggesting that Caprine should add “Marketplace"

Oh god, no, please, no bloat.

**Comment by dusansimic** [comment]
@stamatgeorge sorry for the delayed response. It is in fact the same platform but it's not the same application. Take for example Instagram application and website. Application has a feature to post Instagram stories but form what I know, the website doesn't have that feature. Just because something is the same platform, doesn't mean all applications will have the exact same features.

As for Caprine "adding" the Marketplace feature, we don't plan on adding any new major features to the app since it's mainly meant as a wrapper around all the features that messenger.com already has. Besides, it would take an extreme effort to implement it for which we do not have resources.

**Comment by stamatgeorge** [comment]
@dusansimic No worries. I understand now. Thanks for everything you guys do.
