### ISSUE TITLE
Desktop notifications are back, but firing for muted chats

### ISSUE THREAD

**Issue by HugLifeTiZ** [sindresorhus/caprine#1798]
Well, looks like Messenger for web **finally** brought back desktop notifications. However, they are firing for muted chats just as well as unmuted chats. I provided them some feedback, but I have absolutely no faith that they'll actually do anything with it since it took them this long to bring them back in the first place. Can this be worked around in Caprine somehow?

**Comment by dusansimic** [comment]
Are there notifications in the regular web browser on messenger.com? If there are, then we'll look into it once developers get access to that feature since afaik none of us do (at least I don't). If there are no notifications in the browser it might be our issue since at some point that feature was added again but it was a bit clunky and was basically a workaround.

**Comment by HugLifeTiZ** [comment]
There *used* to be, but they're gone again. Don't know what to tell you, sorry. Guess I'll close for now. :/
