### ISSUE TITLE
white window

### ISSUE THREAD

**Issue by lashkevi** [sindresorhus/caprine#1803]
Caprine shows white window (only the menu is visible above). I also tried the last version (2.55.4) and to remove the ~/.config/Caprine directory. No effect.

---

Caprine 2.45.0
Electron 8.2.1
linux 5.3.18-150300.59.54-default
Locale: r
![Screenshot_20220331_132137](https://user-images.githubusercontent.com/13115223/161034459-787c1726-aa70-43b5-9175-20ddaedc5c00.png)
u

**Comment by nicohell** [comment]
Same issue on a Rocky Linux 8.5 with AppImage versions  2.7.0, 2.6.0, 2.55.4
I read a post explaining that this issue started after v2.3.1 so I tried caprine-2.31.0-x86_64.AppImage and it works. 
Unfortunately it looks like v 2.31.0 does not status nor notifications badges  (I have no sound)
For truth the issue is not exactly the same, there are shaded and opacified elements blinking on the page  
![caprine_2 7 0](https://user-images.githubusercontent.com/7948533/166496376-1312388e-5e29-42be-b8cd-c6e1700354b0.png)

**Comment by nicohell** [comment]
Well this morning Caprine-2.55.4.AppImage is working fine...
My précédent post was on 2022-05-03 so "dnf history" does not show any modifications that could explains that :
![image](https://user-images.githubusercontent.com/7948533/167582819-d2fad7f8-050d-42e2-b59e-4f57018c74cd.png)
