### ISSUE TITLE
Can't open Image Preview

### ISSUE THREAD

**Issue by Hugomguima** [sindresorhus/caprine#1806]
Left Mouse Click a screenshot someone sent
A black screen pop-up window is brought on instead of the image

---

Caprine 2.55.4
Electron 13.6.9
linux 5.17.1-arch1-1
Locale: en-US

**Comment by kamack38** [comment]
I can't do that either on Windows.

**Comment by ashleywaite** [comment]
Happening to me too and appears to be an old bug come back to life, probably due to some class name or style changes FB made. It happened back in Nov/Dec in issue #1751 

The fix that worked last time from _@RishabSwift in https://github.com/sindresorhus/caprine/issues/1751#issuecomment-986915656_ works again for me.

Open the electron dev tools (this is crtl-shit-I for me on Ubuntu) and remove the `hide-preferences-window` class from the `<html>` element. Works until you close Caprine and open it again.

![ScreenShot 2021-12-06 at 11 01 45@2x](https://user-images.githubusercontent.com/15897093/144879634-be4eee24-3d76-40c4-80b0-2951b1bb6c93.png)

**Comment by kacnje** [comment]
I have the same problem (Caprine 2.55.2 on Linux Mint). The workaround (remove "hide-preferences-window" class) works. 
Waiting for the new version ...

**Comment by kamack38** [comment]
> Happening to me too and appears to be an old bug come back to life, probably due to some class name or style changes FB made. It happened back in Nov/Dec in issue #1751
> 
> The fix that worked last time from _@RishabSwift in [#1751 (comment)](https://github.com/sindresorhus/caprine/issues/1751#issuecomment-986915656)_ works again for me.
> 
> Open the electron dev tools (this is crtl-shit-I for me on Ubuntu) and remove the `hide-preferences-window` class from the `<html>` element. Works until you close Caprine and open it again.
> 
> ![ScreenShot 2021-12-06 at 11 01 45@2x](https://user-images.githubusercontent.com/15897093/144879634-be4eee24-3d76-40c4-80b0-2951b1bb6c93.png)

Worked for me on Windows

**Comment by orucky** [comment]
Curious question/suggestion in https://github.com/sindresorhus/caprine/issues/1811#issuecomment-1096977599.
