### ISSUE TITLE
Issue with displaying images.

### ISSUE THREAD

**Issue by Blady0** [sindresorhus/caprine#1811]
I used this app for a few weeks i installed it on a few of my computers different OS from 7 to 10 . 
The issue started in recent days , when i try to open the image in full view nothing displays. It's just a blank window from the app. 
It happens on all of the computers i use.

---

Caprine 2.55.4
Electron 10.4.7
win32 10.0.19044
Locale: pl

**Comment by czerwinski76** [comment]
Same here. 

Latest W10 x64.
Caprine 2.55.4

**Comment by RishabSwift** [comment]
This issue was previously mentioned (#1751)

> For now, my workaround has been opening Developer tools (Command + Option + I on mac, Ctrl + Shift + I for windows) and removing the `hide-preferences-window` class from the `<html>` tag.
> Works until you close Caprine and open it again.


![](https://user-images.githubusercontent.com/15897093/144879634-be4eee24-3d76-40c4-80b0-2951b1bb6c93.png)

**Comment by jbartos** [comment]
Same here.

W10 x64
Caprine 2.55.4

Workaround mentioned by @RishabSwift is working, thanks.

**Comment by orucky** [comment]
What exact effect would it have if the class was never added (see https://github.com/sindresorhus/caprine/issues/1751#issuecomment-988665427)? Is it purely for aesthetic purposes?

If my vague understanding is correct, the code of Caprine that handles this must match the content served by Facebook in order to work correctly, and as the latter changes without prior warning and in an unexpected way, this bug can never be reliably fixed?

If the answer to both questions is _yes_, could the functionality be prioritized over appearance, i.e., the class manipulation removed?

**Comment by lefterisgar** [comment]
Hi guys! You could try using my [fork](https://github.com/lefterisgar/caprine/releases/tag/v2.55.4-3) until the pull request is merged upstream.
