### ISSUE TITLE
Click on Screenshot/Blank Screen

### ISSUE THREAD

**Issue by PreachJohn** [sindresorhus/caprine#1814]
Something strange two times now lately. 
1) Click on a screenshot of a Text conversation or...
2) Click on a screenshot of a Twitter conversation.
Both incidents Caprine goes to a blank screen.
The only escape is to Relaunch.

---

Caprine 2.55.4
Electron 10.4.7
win32 6.1.7601
Locale: en-US

**Comment by lefterisgar** [comment]
I hope [this](https://github.com/lefterisgar/caprine/releases/tag/v2.55.4-3) works for you. The fix will soon be merged here as well though.

**Comment by PreachJohn** [comment]
Now the Remove Button is not working. And the Text Image mentioned is still just opening a blank screen.
Or am I missing that this will all be fixed 'soon'?

**Comment by lefterisgar** [comment]
Well I have to admit that I'm not sure. I just packed the fix into an executable before Caprine gets a new release. The fix is not mine so I just thought it would resolve your issue. Can you send a screenshot of the problem? I'm not able to replicate it.

**Comment by mquevill** [comment]
@PreachJohn If you are wanting to test a fix, you need to install the forked package from @lefterisgar. (Once installed, go to the menu Help > About Caprine and it should read "2.55.4-3".)

These changes (#1815) have not been merged in with the main codebase yet, so the only way to test them is to build from source or use the packaged version from @lefterisgar (https://github.com/lefterisgar/caprine/releases/tag/v2.55.4-3). If your version in Help > About Caprine reads "2.55.4", this issue is not fixed in that version.

**Comment by PreachJohn** [comment]
The Pkge does not install.

PreachJohn

**Comment by mquevill** [comment]
You may have to wait until an official release has been made then.

**Comment by lefterisgar** [comment]
Yeah you may need to wait as I also don't have a Windows VM to test. Installs fine on wine though.
