### ISSUE TITLE
Tray Icon - No notification badge

### ISSUE THREAD

**Issue by maxoku** [sindresorhus/caprine#1823]
From almost a year badges don't work. I don't understand why no one cares to restore this essential feature?
---

Caprine 2.55.4
Electron 10.4.7
win32 6.3.9600
Locale: pl

**Comment by SilverSaw** [comment]
I can confirm it is not working and this is the only feature i am looking for 2.56.1

**Comment by maxoku** [comment]
@lefterisgar It's not only about tray i con badge but also and mostly about taskbar icon.

**Comment by SilverSaw** [comment]
2.57.0 and this bug is still here, we are unable to understand when we have messages or not. Could you please prioritize this? There is also another conversations for the same issue here: 
https://github.com/sindresorhus/caprine/issues/1562
https://github.com/sindresorhus/caprine/issues/1159

**Comment by elofu17** [comment]
I too need the tray icon dot/badge!

Since we hear a sound when a new message arrive, it must be possible to also change the tray icon to show a red dot (like Slack) at the same time.
The question is how and when the dot (badge) should be removed. Preferrably when all unread messages have been read, if possible. Can't this be done by tracking the status of unreads, client-side?

**Comment by wokawoka** [comment]
I'm experiencing the same problem

**Comment by PrimozR** [comment]
Is there a setting related to any of this? I haven't had either the tray or the taskbar icon showing any notifications... ever?
