### ISSUE TITLE
Notifications and tray indicator are broken

### ISSUE THREAD

**Issue by ienzo** [sindresorhus/caprine#1825]
Linux Mint 20.3 Cinnamon 5.2.7 on Linux 5.13.0-40-generic if it helps. I installed using the deb package.

**Comment by Neo-29** [comment]
Same on gnome 42...
Archlinux
No notifications shown anywhere
Make this app ( messenger) useless on my desktop

**Comment by dusansimic** [comment]
Probably the workaround is broken because of some redesing on the Messenger website. Since there are currently a lot of issues to fix which have a higher priority, this will have to wait.

**Comment by dusansimic** [comment]
This issue is present on all platforms. It is caused by Messenger website not sending browser notifications so we need to work around that and scrape the website for information about new messages. This is a bad workaround which is prone to breaking because it relies on the ui which changes from time to time but it's the easiest solution. A long term solution (if Messenger website doesn't implement browser notifications) is decoding the websocket communications which was worked on #1688 (by solving this issue we would also solve privacy mode issues). It's a big undertaking but if it's done at some point it would solve a lot of problems.

As for when it will be done, no one knows at the moment since we don't work full time on this. Feel free to work on some issues if you're able so we can spend more time solving these problems :)

This is just an elaboration what is the issue here so we can link any new bug reports here.

**Comment by Naimad1CZ** [comment]
Just some (maybe useful?) info:

1) The sound of new message works fine (at least on Windows 10, Caprine 2.56.1).
I don't know much how Caprine works, but theoretically the check for a new messages count could be somehow bound to this sound + done when reopening Caprine + when the PC gets waked from sleep/hibernation. Oh, but this should also be updated when I read some message e.g. on my phone. Soo probably some frequent repeating task that scrapes chats and counts "bold" chats that are not muted? It might not work accurately when someone has some old unread chats, but I for me, it would be a good solution.

2) My dirty workaround is to have both Messenger desktop and Caprine open, right next to each other on taskbar, and when I see the indicator of a new message on Messenger desktop or hear the sound of new message, I just maximize Caprine app.

**Comment by ienzo** [comment]
> My dirty workaround is to have both Messenger desktop and Caprine open, right next to each other on taskbar, and when I see the indicator of a new message on Messenger desktop or hear the sound of new message, I just maximize Caprine app.

That's what I do too. My browser is Vivaldi and it has messenger open and notifications work.

**Comment by dusansimic** [comment]
> That's what I do too. My browser is Vivaldi and it has messenger open and notifications work.

You mean that in the Vivaldi browser, notifications on the website work (a bubble pops up in the os)?

**Comment by ienzo** [comment]
That's right. It does. I'm on Linux and Vivaldi gives me notifications on things.
