### ISSUE TITLE
Releasing a new version is flaky

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/caprine#1848]
I have tried doing the release 5 times now. It always leaves out some of the assets.

**Comment by Alex313031** [comment]
@sindresorhus Another issue with latest .deb release. The GPU sandbox isn't working, which is tied into the main sandbox in chromium/electron. Running it shows [174419:0617/155833.134464:FATAL:gpu_data_manager_impl_private.cc(442)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap

Even after using sudo chown root chrome-sandbox && sudo chmod 4755 chrome-sandbox it still doesn't work. 
Running caprine --no-sandbox works fine though.

Looking deeper it seems the deb is already setting the correct permissions for the sandbox, but the gpu process is still unable to use it.

**Comment by lefterisgar** [comment]
@Alex313031 Check #1805 for a possible explanation.

**Comment by sindresorhus** [comment]
@lefterisgar Mostly random failures like here: https://github.com/sindresorhus/caprine/runs/6926596699?check_suite_focus=true

**Comment by dusansimic** [comment]
The issue seems to be that snapcraft is not installed which is triggered by electron-builder trying to build a snap package. Snapcraft is not installed since the installation and configurations step in ci was removed (https://github.com/sindresorhus/caprine/commit/529c2b40e83a6618bae055bb3f8e5e984f5c21d3) however the snap target is still present in package.json (https://github.com/sindresorhus/caprine/blob/main/package.json#L123).

**Comment by lefterisgar** [comment]
It looks like I didn't have that issue because I ran electron-builder directly with this command: `node_modules/.bin/electron-builder`

**Comment by dusansimic** [comment]
@lefterisgar 

> It looks like I didn't have that issue because I ran electron-builder directly with this command: node_modules/.bin/electron-builder

On this repo GitHub Acitons is used to publish the release and packages (which is where the issue occurred) which your fork doesn't use from what I can see.

> On a sidenote, we should consider dropping the snap build because it hasn't been updated in a year and a lot of people who don't know, use that and then experience issues that have long been fixed.

I don't agree with that. The issue is not with the snap package itself, rather publishing of the snap package which is caused from what I can guess by outdated login token. Once the latest version gets published, the problem will go away :grin:. It would be ideal if someone who uses Linux would get access to the package on snap store so they could maintain the publish process to it. I could do that if that's fine.

**Comment by sindresorhus** [comment]
> I could do that if that's fine.

That would be great. I have sent you an invite.

**Comment by dusansimic** [comment]
> I have sent you an invite.

Fantastic. I'll see if I can handle it tomorrow.

**Comment by lefterisgar** [comment]
@dusansimic
> On this repo GitHub Acitons is used to publish the release and packages (which is where the issue occurred) which your fork doesn't use from what I can see.

Thanks a lot for the introduction! I haven't used GitHub Actions before so it was very helpful to tell me what exactly is going on.

> I don't agree with that. The issue is not with the snap package itself, rather publishing of the snap package which is caused from what I can guess by outdated login token. Once the latest version gets published, the problem will go away grin. It would be ideal if someone who uses Linux would get access to the package on snap store so they could maintain the publish process to it. I could do that if that's fine.

That's fine. Didn't know it was that easy to fix it. At least now a lot of users won't open unnecessary issues related to the snap build. It's also nice you stepped in and offered to maintain the snap package.

**Comment by lefterisgar** [comment]
Also, I believe that since there have been introduced a lot of changes (including a significant bump in the Electron version) we should hold the release for a few days to sort out any remaining issues and then release a minor version, not a patch.

**Comment by dusansimic** [comment]
> Thanks a lot for the introduction! I haven't used GitHub Actions before so it was very helpful to tell me what exactly is going on.

No problem! The basic idea is to avoid doing repetitive tasks that can be automated easily. Of course with every system come some issues so here we are 😅 but there are a lot of benefits (testing builds, linting code, publishing releases). In ideal cases you shouldn't worry about ci/cd bot it's quite useful to get to know it.

> Also, I believe that since there have been introduced a lot of changes (including a significant bump in the Electron version) we should hold the release for a few days to sort out any remaining issues and then release a minor version, not a patch.

Absolutely agree with that! I'd prefer if possible that we test out the app ourselves for a few days after sorting everything out so we can be sure that we don't introduce any unexpected bugs. Also it would be ideal to test it on as many systems as possible (especially Linux distributions). I'm currently on vacation so I can only test it on Fedora but I'll see if anyone else might be able to test a few dev builds.

**Comment by lefterisgar** [comment]
Perfect! You will test on Fedora, I daily-drive Kubuntu. That should cover most cases but if I find the time I will spin up a Manjaro VM. Would you think it's a good idea to create a PPA?

**Comment by dusansimic** [comment]
> Would you think it's a good idea to create a PPA?

Oh well, that is a tricky question, especially since I maintain Flatpak and RPM packages myself. I'll open a new issue to discuss that and write my thoughts on it and distributing Caprine through other repositories as well.

**Comment by dusansimic** [comment]
@lefterisgar actually, let's avoid unnecessary prolonged discussions. In my opinion, PPAs and third party repos in general have a lot of downsides. Package maintenance should be if at all possible done in official repos (https://github.com/sindresorhus/caprine/issues/1458). Flatpak, Snap and AppImage packages are meant to be distributed by the program author but other packages are just easier to be distributed by the distributions. I've already wanted to start the process of publishing an rpm package to Fedora repos but it just takes a lot of free time which I don't have at the moment.

If you'd like to publish the package to the deb package to the PPA, I can't stop you 😄. I'm doing the same thing for rpm package on COPR, so we could try it. You should just know that it's a lot of unforgiving work which might not pay off as much as you give. I personally maintain packages for Fedora, Arch and some Flatpak packages and I don't plan on doing Ubuntu too so that would be mostly in your hands.

**Comment by lefterisgar** [comment]
@dusansimic I mean I had the initial idea to create the PPA but as you said it's another responsibility and it might not pay off. Especially when Caprine is already included in the deb-get index where releases from GitHub are automatically distributed without any effort at all.

>  You should just know that it's a lot of unforgiving work which might not pay off as much as you give.

Isn't the majority of Linux users using Debian?

> I'm doing the same thing for rpm package on COPR, so we could try it.

Yes we could give it a shot and just see how it goes. Maybe automating the entire process would help.
