### ISSUE TITLE
FATAL:gpu_data_manager_impl_private.cc

### ISSUE THREAD

**Issue by tpchuckles** [sindresorhus/caprine#1861]
I receive the following error when trying to launch caprine:

`athena@everest:~$ caprine
[121132:0719/092533.935616:FATAL:gpu_data_manager_impl_private.cc(442)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)`

uninstalling/purging/reinstalling ("sudo apt-get remove caprine", "sudo dpkg --list |grep "^rc" | cut -d " " -f 3 | xargs sudo dpkg --purge", "sudo dpkg -i caprine_2.55.6_amd64.deb") didn't resolve it. 

although I did find [this workaround](https://github.com/Automattic/simplenote-electron/issues/3044#issuecomment-1122225678) : "caprine --no-sandbox" seems to allow it to run.

**Comment by tpchuckles** [comment]
> considered to be insecure

pardon my ignorance, but what does "insecure" mean in this context?

that a process running inside the containerized(?) browser instance could escape since it's unsandboxed? if the only web page is from a trusted source (facebook, i suppose), is this still a concern?

**Comment by lefterisgar** [comment]
You are effectively disabling Chromium sandbox, a security feature. This website explains the potential security risks: https://no-sandbox.io.

Moreover, the official version of Caprine still ships with Electron 10 which is past EOL which in turn means NO SECURITY fixes. Would you use a browser that hasn't received any update since May 24 2021? It's the same thing. In contrast, the linked fork ships with the latest Electron version (19) and you just can't imagine how vulnerabilities have been discovered and patched since then.

**Comment by lefterisgar** [comment]
Closing, as it will be fixed in the next release.
