### ISSUE TITLE
[Feature Request] Add HTML ID to elements

### ISSUE THREAD

**Issue by Lilypad64** [sindresorhus/caprine#1911]
when checking the Developer Tools, it seems that Messenger Web uses Bootstrap/Tailwind like classes where it's hard to find the right element to theme and most classes' names are obfuscated. My idea is that adding HTML IDs to elements so theming doesn't affect other elements as well.

I know that it might be difficult to implement but if it's possible it would be appreciated.

**Comment by dusansimic** [comment]
That would definitely be ideal but we would still need to find those element the way we're doing it now (through those obfuscated class names) since we can only modify the page source once it's loaded. It wouldn't really solve the issue, just add an extra step to the current solution which would make it more difficult to maintain.
