### ISSUE TITLE
Scroll speed

### ISSUE THREAD

**Issue by Pheggas** [sindresorhus/caprine#1926]
Hello, it is possible to customize scroll speed withing the app? It seems really slow to my taste and id like to customize it.

**Comment by dusansimic** [comment]
We don't have that feature implemented in Caprine, it's probably an issue with Chromium (the browser used to render stuff in Electron which we use for Caprine). It seems that there are some issues online about this but I haven't found a definitive solution for it. Since it's unrelated to Messenger/Caprine (it's related to Electron and Chromium), I'll close this as won't fix.
