### ISSUE TITLE
[FEATURE REQUEST] Conversation pinning

### ISSUE THREAD

**Issue by ayakael** [sindresorhus/caprine#1952]
Would it be feasable to add the ability to pin conversations? I unfortunately have to use Facebook for work and it would be nice to have certain conversations always on top to keep track of the most important. Thank you for all the work!

**Comment by dusansimic** [comment]
Unfortunately, that feature would be a bit problematic. The thing is we don't have access to all conversations, just those that are currently visible. Those we could possibly pin but only if they are visible when starting the app and initially loading it. If they are not visible (for example there are enough newer conversations that the one that is pinned is far down so it's not shown initially), we would not be able to pin them on startup.

This feature would better be requested on Messenger/Facebook website and their services. We don't want to partially implement a feature that won't really work perfectly and also have to maintain it with already present features that need maintenance and fixing.

I however hope that Messenger implements this since it would be quite a useful feature :)
