### ISSUE TITLE
Links opening in some kind of internal browser?

### ISSUE THREAD

**Issue by maetthew** [sindresorhus/caprine#1982]
Hi,

I'm not sure when this started happening. But lately when I'm clicking links in a chat they open in some kind of internal browser of Caprine's?

I can't find a setting to change this and have to copy paste links into my browser. Is this behaviour intended?

I'm on Arch Linux, Caprine 2.57.0. Not sure what other information needs to be provided but happy to provide if needed.

**Comment by dusansimic** [comment]
This is very unusual. I don't experience this behavior (I also use Arch Linux). What you should experience is link being opened in the default browser. Check if you have a default browser set.

Also, could you send here an example of a link that is misbehaving? I'd like to see if it's related to the specific link.

**Comment by maetthew** [comment]
All the links that I've clicked last couple of days are opening in this 'internal' browser for some reason. All links from all other apps (Telegram, Discord, Thunderbird etc) are opening in my browser as normal.

I'm using KDE and my browser is set in "Default Applications" under "System Settings", also my `BROWSER` environment variable is correctly setup (and has been for at least a year).

**Comment by maetthew** [comment]
I've also tried deleting settings and app data, to no avail. Maybe I should try to reinstall completely. I'm experiencing other weird behaviours like a lot of the menu items seems to have no effect what so ever, like none of the options under "Conversation" works. Under "View" I can't change theme or change sidebar settings for instance.

**Comment by maetthew** [comment]
FWIW I uninstalled Caprine, and nuked the config folder, with no effect.

**Comment by dusansimic** [comment]
Facebook usually partially rolls out new things on the messenger website so that's why I didn't have the same behavior. Now it happens on my account too.

**Comment by dusansimic** [comment]
I'm now able to reproduce this behavior. I can't guarantee when it's going to be fixed but help is welcome.

**Comment by SlouchyButton** [comment]
This is the default behavior of electron, and is probably not related to Facebook Messenger in any way.
This might be broken because Caprine uses system electron instead of prepackaging one and is not tied to a specific version, but rather uses the default electron on system (most likely the most recent one). There was a breaking API change in electron, that deals with how to deal with new window opens. I did not check how Caprine handles this, but I encountered this while doing my own Messenger app, because most tutorials use old API.

https://www.electronjs.org/docs/latest/breaking-changes#removed-webcontents-new-window-event

Correct way of handling of link open (better said new window open event) is like this now:
```
win.webContents.setWindowOpenHandler((details) => {
        // THE ACTUAL SUMMONING OF EXTERNAL BROWSER GOES HERE
        // e.g: shell.openExternal(details.url); // open link externally
        return { action: 'deny' } // deny the request to open new window in electron
})
```

**Comment by dusansimic** [comment]
Thank  you @SlouchyButton for investigating the issue! I'll see if I can fix it this weekend but PRs are very welcome!

**Comment by jernejsk** [comment]
This doesn't seem to work for me on Arch - I'm using Caprine 2.57.2 with electron 22.3.3 on KDE Plasma wayland. Is there any additional setting to check?

**Comment by SlouchyButton** [comment]
> Fix doesn't seem to work for me on Arch - I'm using Caprine 2.57.2 with electron 22.3.3 on KDE Plasma wayland. Is there any additional setting to check?

@jernejsk @dusansimic I have tried to download repo after the update and compile it to try myself and @jernejsk is indeed right. The fix does not work, and links still open in a new electron window.

**Comment by xrtxn** [comment]
> > Fix doesn't seem to work for me on Arch - I'm using Caprine 2.57.2 with electron 22.3.3 on KDE Plasma wayland. Is there any additional setting to check?
> 
> @jernejsk @dusansimic I have tried to download repo after the update and compile it to try myself and @jernejsk is indeed right. The fix does not work, and links still open in a new electron window. I'd reopen this issue and investigate further.

It doesn't work on arch for me too. It just opens it in a new electron window.

**Comment by maetthew** [comment]
Can confirm here also, experiencing the same behaviour with the fix applied.

**Comment by SlouchyButton** [comment]
Please do not spam the thread, with "Me also" comments, because it doesn't really help too much. We know the problem exist, and without more information, those messages won't help us.

If you have the same problem, but have no new or possibly important information, please use reactions on comments to show that you are having the same problem. That way, devs know it is not an isolated case, but important comments and information won't be buried under lots of other comments.

**Comment by dusansimic** [comment]
Thanks for the quick responses. New version is in the Arch repos so please check if the issue is fixed. For me, it works fine now.
