### ISSUE TITLE
set background opacity to get blurred effect on linux with picom, css ? [1327]

### ISSUE THREAD

**Issue by NicTanghe** [sindresorhus/caprine#1990]
Hello,

I’d like there to be a background opacity setting.
Can you do this is the css file ?
If so how?

ticked [1327](https://github.com/sindresorhus/caprine/issues/1327) was closed for an incorrect reason.

You don't need to implement anything aside from background transparency and the other program, picom.
Will handle the rest. It is definitely supported and there was no valid reason to close the ticket.

**Comment by dusansimic** [comment]
Vibrancy is not the same as transparent/blurred background and it shouldn't be put under the same option in that sense. Regarding the implementation, the problem is not with compositors that support blur rather with ones that don't (e.g. Mutter). In order to maintain platform consistency there should be a blur feature for both compositors that support blur and those that don't. Afaik, there is no such support (event through some external libraries) for Linux. Besides that our focus currently is on maintaining and fixing present features, not adding new ones.

Everyone is however free to work on making Caprine able to have transparency and through compositors that support it, blur. It should be possible by modifying the website stylesheet and enabling transparency for Electron window.
