### ISSUE TITLE
257.2 WILL NOT Install

### ISSUE THREAD

**Issue by PreachJohn** [sindresorhus/caprine#2009]
Help! 257.2 WILL NOT install on my Computer. The DLL No Entry Point Notice comes up each time.
I have had to reinstall 257.0 and to uncheck Automatic Update.
My fix  works for now, but for how long?

---

Caprine 2.57.0
Electron 21.2.3
win32 6.1.7601
Locale: en-US

**Comment by dusansimic** [comment]
Please supply all error messages here. The issue can't be investigated without them.

**Comment by Alex313031** [comment]
@dusansimic @PreachJohn This is because you updated electron to 24, which is based on chromium 112. Chromium and all derivatives ended support for Windows 7/8/8.1 with Chromium M110. 109 and hence electron 22 is the last version for these platforms. I just came here to file an issue about this because I use windows 7 on some of my machines.

You should either, 1. downgrade electron to 22, since it is still getting updates until october of this year, or 2. Add something in the code to check for the NT versions and disable updates past 2.57.1. 3. you should also add a button or way to configure updates on windows in general, since sometimes people want to have manual control over updates (like me)

**Comment by Alex313031** [comment]
@PreachJohn If they dont want to downgrade electron, I have a fork here > I can keep it on electron 22 for us users on win7/8/8.1 or derivatives like windows server 2008 R2, 2012, 2012 R2, etc.

**Comment by dusansimic** [comment]
Closing in favor of #2011

**Comment by PreachJohn** [comment]
Please keep me in the Loop if a Fork becomes necessary.
For now I use 257.0 as I can't find a Copy of 257.1 anywhere, the last
version of course that did install on my Computer; Win 7 Pro 64 bit.
John Butkans

**Comment by PreachJohn** [comment]
On Win 7 Pro 64 bit, after 2.57.1 this is what appears.

**Comment by PreachJohn** [comment]
Alexander David Frick has a clear understanding as to why versions beyond 257.1 will not install on Win7 Pro 64 bit; don't code further than electron 22.
Happily I came here to Github's Site. Cause I see a download link for me that did not come thro' in the email copy I received from Mr. Frick. Obviously a bright Individual as the regular listed Contributors to Caprine are too.

**Comment by Alex313031** [comment]
@PreachJohn New repo specifically for Windows 7 releases > https://github.com/Alex313031/caprine-win7
