### ISSUE TITLE
Tray icon/indicator Fix

### ISSUE THREAD

**Issue by stkrknds** [sindresorhus/caprine#2031]
Hello everyone. I was able to find a fix for the issue where the tray icon does not indicate if there are any unread messages(related issues #1995, #1825, #1823). I'm reluctant to open a pull request because I'm a complete newbie to ts/js/electron (I've been working on this for a few days) and I'm not sure about the quality of the code.

From what I understand, there seem to be two problems:

- The observer, which "observes" the sidebar, does not trigger when the conversation list changes.

- The conversation list selector is not receiving the actual list of the conversations.

The commit:
https://github.com/stkrknds/caprine/commit/31c6fec71e544832fbe3a57dab2d9fb7b33a71e9

As I said, I don't know much about web development, so the code is probably lacking in quality. I would appreciate it if someone could take a look at it and suggest improvements.
Thank you very much for your time. 
![Unread Icon](https://github.com/sindresorhus/caprine/assets/69848524/5dae87a0-d28e-4461-b184-0e9afdcb870e)

**Comment by wallneradam** [comment]
Hello, I've tried your modifications and unfortunately the tray icon remains if I get a message.

**Comment by stkrknds** [comment]
Hello @wallneradam. What

**Comment by stkrknds** [comment]
Hello @wallneradam . What language do you use in Messenger?

Sorry about closing and reopening the issue. Missclick.

**Comment by wallneradam** [comment]
I'm using it in Hungarian. Just looked at it again and see there is a dictionary with language codes. I added my language code to it and now waiting for a message...
I'm also not an Electron developer, though working with JS a lot. I would add a fallback to line 239 to use english if the locale is not in the dictianary.

**Comment by dusansimic** [comment]
Hi @stkrknds. Thanks for the contribution and the time you took to look over the issue and figure out your way around the codebase! 😄

The problematic thing about your implementation is that it relies on the display language to work. `aria` tags are used for accessibility features, not really for querying elements. What we mostly rely throughout the project are class names and role tags ([example 1](https://github.com/sindresorhus/caprine/blob/main/source/browser/selectors.ts), [example 2](https://github.com/sindresorhus/caprine/blob/main/css/browser.css)). This way it works for any display language but it does require us to monitor the page source changes (class name changes) and fix the query selectors accordingly.

Since both the observer and a query that gathers all the conversations rely on correct selectors, fixing them in a more universal way (for now we think it's roles and class names) would work for any display language. If you're interested in working on this issue, that would probably be a way to go. I understand you're not a web developer but I'm here if you need any pointers 😄.

Thanks again for the time and effort you invested into this issue!

**Comment by stkrknds** [comment]
Yes @wallneradam , you need to add your language to the dictionary. First you need to find out what  the 'Mark as read' and 'Chats' strings are in Hungarian and then add them to the dictionary:
```
const translationDict = {
	hu : {markRead : 'String here',
		 chats : 'String here',
	     },
};
```
You don't have to wait for a new message, you can mark a conversation as unread(click on the three dots) and test it that way.

**Comment by stkrknds** [comment]
Hello @dusansimic. Yes I understand that this implementation is indeed problematic. I will try to find another way, that doesn't rely on aria tags. But, if I'm not mistaken, the current implementation of Caprine(without the changes), uses this to check if a conversation is unread. 
`conversation.unread = Boolean(element.querySelector('[aria-label="Mark as Read"]'));`
So I modified it to work with different languages😁.

**Comment by stkrknds** [comment]
Hello there. I have replaced the aria labels, with class names/roles. Now it works fine regardless of the display language. Again, the code probably needs improvement.

https://github.com/stkrknds/caprine/commit/50a1f2058bc7c487ce72f7d77b67badb18f8d3c9

There is also another way to update the tray icon. Instead of parsing the conversation list, we could just check the Chats icon(in the left sidebar). Do you think something like this would be a good idea?

Thanks for your time.

**Comment by dusansimic** [comment]
@stkrknds thanks for the contribution again! The code looks nice, however there are some things that should be changed but linter will probably tell you about that. You can run `npm run test` and see what should be changed.

> There is also another way to update the tray icon. Instead of parsing the conversation list, we could just check the Chats icon(in the left sidebar). Do you think something like this would be a good idea?

That's a good idea! I think this solution is fine as a fix but if you'd like to try and fix it by checking out the icon, that would be great!

Could you send the solution via a pull request? GitHub workflow will automatically run all the tests on the code so we can make sure that everything is in order before getting merged.

**Comment by stkrknds** [comment]
Hello @dusansimic. I've implemented a fix by utilizing the "Chats" icon. It requires some big changes, but I find this implementation superior to the previous one. It's much simpler to get the number of unread messages, more stable and additionally, we don't have to worry about muted conversations, because messenger does the work for us. I would like to hear your thoughts. Thanks again for your time.
https://github.com/stkrknds/caprine/commit/c0b1c56f7b402fd410f57fffdf3c3978e320f3ba
