### ISSUE TITLE
Make linux app version more native and support GTK/QT instead of CSS.

### ISSUE THREAD

**Issue by shawny43** [sindresorhus/caprine#2048]
If Caprine can being native with MacOS that include vibrancy, why we didn't got enhancement with GTK/QT support where we can get similar features to MacOS versions but in linux style. It's could be nicer for the theme design of our Desktop. Example, i would see some adwaita or breeze inside a caprine natively without messing up with the css code.

**Comment by dusansimic** [comment]
App is a wrapper around a webpage. That's why we use Electron. Electron has more native features supported on macOS than on other platforms.

> why we didn't got enhancement with GTK/QT support where we can get similar features to MacOS versions but in linux style

That would mean rewriting everything, which is not a plan at the moment (https://github.com/sindresorhus/caprine/issues/1971). Also, using native libraries (GTK and Qt) to make an apps would require scraping the webpage instead of the user interacting with it which makes a completely different idea for the app.

> It's could be nicer for the theme design of our Desktop.

The same thing could be done by using custom css to style the webpage. There was a pr for CSD for Adwaita https://github.com/sindresorhus/caprine/pull/1543 but it fell through due to lack of activity.
