### ISSUE TITLE
Notifications stopped working

### ISSUE THREAD

**Issue by elofu17** [sindresorhus/caprine#2084]
Hi!
This is as much a question as it is an issue report.

I'm using Caprine v2.59.0 on Windows 11.
For the last weeks I have had working notifications. Yay! :-)
* the black and white icon in the systray becomes a colorful icon when there are unread messages
* if the Caprine window is open, the icon on the taskbar show a badge when there are unread messages

But for the last couple of days these notifications don't work any more. :-/

A couple of days ago (on Oct 7 2023) I installed a major update (22H2) to Windows 11.
Is it perhaps this update that stopped the notifications from working?
(or could it be some forced settings from my organisation that now block the notifications that worked last week?)

Do anyone else experience the same?

**Comment by dusansimic** [comment]
@elofu17 

> Is it perhaps this update that stopped the notifications from working?

Unlikely. Features usually stop working when Facebook changes something in the website ui because Caprine (especially notification feature) heavily depends on some specific structures and class names in the ui.

Issue was already reported in https://github.com/sindresorhus/caprine/pull/2051 but thanks for opening an issue 😄.

We'll fix this asap.

**Comment by elofu17** [comment]
Just confirming that in v2.59.1 notifications are working again. :-)
Thanks!

**Comment by mzso** [comment]
It's working but the colored icon often erroneously,persists even if I click on it and see the message.
I have to click on it multiple times to open/hide the window. Or click around the window, switching between contacts and such, selecting the input field (I think).
