### ISSUE TITLE
Norton detected security issue

### ISSUE THREAD

**Issue by D3V4N5H** [sindresorhus/caprine#210]
Filename: caprine-setup-2.3.1.exe
Threat name: WS.Reputation.1

____________________________

____________________________

On computers as of 
16-May-17 at 6:33:08 PM

Last Used 
16-May-17 at 6:35:09 PM

Startup Item 
No

Launched 
No

Threat type: Insight Network Threat. There are many indications that this file is untrustworthy and therefore not safe

____________________________

caprine-setup-2.3.1.exe Threat name: WS.Reputation.1
Locate

Very Few Users
Fewer than 5 users in the Norton Community have used this file.

Very New
This file was released less than 1 week  ago.

Medium
This file risk is medium.

____________________________

Source: External Media

Source File:
caprine-setup-2.3.1.exe

____________________________

File Actions

caprine-setup-2.3.1.exe Removed
____________________________

File Thumbprint - SHA:
1073737ac44ead81706777a622d909278e98286398043bead47fbf836b8d5bd7
File Thumbprint - MD5:
f4acc25c78ff6c7f05c3d0560ee9ee8b

**Comment by sindresorhus** [comment]
It's because there's no certificate on the installer. Just whitelist it.

Norton has by the way proven to be a bigger security threat than it solves. You should seriously consider what you're using.

https://www.google.co.th/search?q=norton+proejct+zero&oq=norton+proejct+zero&aqs=chrome..69i57.2746j0j1&sourceid=chrome&ie=UTF-8#q=norton+project+zero

https://community.norton.com/en/forums/wsreputation%C2%A0-crap
