### ISSUE TITLE
Wayland - back to X11 complication

### ISSUE THREAD

**Issue by chevyvan10** [sindresorhus/caprine#2149]
![Screenshot from 2024-03-19 22-13-15](https://github.com/sindresorhus/caprine/assets/96021427/68caa6a4-6b0e-42aa-af0e-855d8663350f)

Tried Wayland mode in Linux Mint... When I switched back to X11 the background for received messages are white on white (in dark mode) - unreadable. Yes, I did reboot my system before switching back to X11. I'm using the Flatpak version of Caprine. Reinstalling didn't change anything, and didn't even log me out. Is there a configuration folder I need to delete to reset all of this?

---

Caprine 2.59.3
Electron 25.9.8
linux 6.5.0-26-lowlatency
Locale: en-US

**Comment by mquevill** [comment]
This is (fortunately) not related to switching between X11 and Wayland. This is due to CSS changes on Facebook's end that need to be "fixed" by Caprine for the dark mode.

See https://github.com/sindresorhus/caprine/issues/2148#issuecomment-2009955607 for some custom styles you can add as a temporary fix.
