### ISSUE TITLE
When you reinstall, why do only the old messages come back and not the new ones?

### ISSUE THREAD

**Issue by ThePit0** [sindresorhus/caprine#2153]
If I delete the program and reinstall it, only older messages that I have recently written disappear.However, they are there in the Facebook messages but not in the caprine program.

**Comment by mquevill** [comment]
This may be due to new methods of syncing messages from Facebook's side. If you have set up a PIN to sync messages, it should ask for that to sync all current messages.

Click on your profile picture in the lower left to access the Menu > Privacy & safety > End-to-end encrypted chats > Secure storage. You'll see a menu like the one below, where you can "Remember this browser" among other options for this feature.
![image](https://github.com/sindresorhus/caprine/assets/17033543/6f3d7ad7-5a69-4f81-8a53-59796e8b88fb)

**Comment by mquevill** [comment]
This is definitely related to the end-to-end encryption. You'll need to enter a PIN, but there are issues with the `hide-preferences-window` class that Caprine adds that (unintentionally) prevent the PIN window from showing up at times.

Closing this issue in favor of #2167.
