### ISSUE TITLE
Logged out when closing app

### ISSUE THREAD

**Issue by bonelifer** [sindresorhus/caprine#2159]
It no longer stays logged in after the app is exited. 

Xubuntu 22.04

**Comment by mquevill** [comment]
I know I've had this issue recently, but it fixes after I log in (with ticking "Remember me" or whatever). If you log in again, does this happen if you exit again?

I'm thinking this might be due to recent changes on Facebook's side for security/privacy, so it may have changed the way that credentials were stored/remembered.

**Comment by bonelifer** [comment]
Fixed. For some reason I couldn't see the checkbox.  I had tried scrolling before but it didn't work. Tried again and could see it. Would be nice if you could set in Caprine to have it try and select it when logging in.
