### ISSUE TITLE
CAPRINE PRO ISSUE

### ISSUE THREAD

**Issue by RPSI1607** [sindresorhus/caprine#2186]
application glitches and always automatically goes to the marketplace tab instead of staying on desired chat tabs.
if any other section of application is clicked it will function properly for about 4 seconds and returns to the marketplace section, please help.
---

Caprine-pro 1.0.0
Electron 21.2.0
linux 6.8.0-31-generic
Locale: en-US

**Comment by jarnalyrkar** [comment]
I may be a dumb dumb, but I don't think there exists an official pro version of Caprine.
Have a try with the regular version downloaded from the releases section.

**Comment by mquevill** [comment]
> I may be a dumb dumb, but I don't think there exists an official pro version of Caprine. Have a try with the regular version downloaded from the releases section.

This is correct. The "caprine-pro" on Snapcraft is not an official release of Caprine, and doesn't even follow the same version numbering as the real package.

While this may be based off of Caprine, the Electron version used would mean it's from a version before v2.57.2.

@RPSI1607 The actual Snap package for Caprine is here: https://snapcraft.io/caprine (However, the version is a bit out of date due to some issues with snap packaging.)
