### ISSUE TITLE
Alexander Frick's 2.57.6 Needs A Fresh Copy

### ISSUE THREAD

**Issue by PreachJohn** [sindresorhus/caprine#2208]
Frick's Version has worked well on my Win7 64 bit install. Yes I am a hold out.
Got quirky/corrupted over time.  I uninstalled and from my Downloads Folder reinstalled.
Now does 3 things wrong. But cannot find a fresh 2.57.6 Copy online.
Is there now an Update to 2.57.6 that will work on Win7?
Does Caprine work on Google's ChromeOS Flex?

---

Caprine 2.57.6
Electron 22.3.16
win32 6.1.7601
Locale: en-US

**Comment by mquevill** [comment]
This is for a fork of Caprine. Please raise this issue on the particular fork you are using: https://github.com/Alex313031/caprine-ng

**Comment by PreachJohn** [comment]
This is an ancient issue and you only respond now? No thanks to you
abandoning Win7.
I moved to Win 11 Pro. Caprine still doesn't work in 2 major ways. Can't
delete or Remove. Did Reinstall.
JohnB

**Comment by mquevill** [comment]
Electron dropped support for Windows 7, so we would need to use unsupported versions of Electron to continue support for Windows 7. Even Microsoft dropped support for that version in 2020, so we cannot keep maintaining outdated versions, which has been stated before.

Regarding recent issues, have you updated to v2.60.3? Several issues were fixed with #2181 and #2257 that probably should address the problems you're facing.

**Comment by PreachJohn** [comment]
FYI no copy of Caprine is available there. Alexander Frick's 257.3, I think
it was is the last to work on Win7.
Only 260.1 is available there. And even 257.6 won't install properly on my
Win7 install.
It appears Alexander Frick has also seen fit to abandon Win7 since no copy
of 257.3 is available anywhere I can find.
So no more hope for Caprine on win7 since my 257.3 copy corrupted.
Thanks,
John Butkans
