### ISSUE TITLE
Duplicated icon in taskbar on Windows

### ISSUE THREAD

**Issue by francoischalifour** [sindresorhus/caprine#26]
Once you pin Caprine to the taskbar on Windows and open it, it shows up a new instance of it.

Quite disturbing.

![caprine_duplicated](https://cloud.githubusercontent.com/assets/6137112/10718855/328305c0-7b7c-11e5-99cd-2e7ce67c4128.jpg)

**Comment by sindresorhus** [comment]
// @iiegor

**Comment by iiegor** [comment]
Related issue: https://github.com/atom/electron/issues/1954.

In atom this was fixed by calling ``app.setAppUserModelId`` but this only works for **Squirrel.Windows**... I think there is no solution for this, actually, without using squirrel :pensive: 

As a temporary workaround/fix until this is fixed, @francoischalifour, you can try executing first the exe and then pinning the opened instance of Caprine.

**Comment by sindresorhus** [comment]
@iiegor Can you open an Electron ticket about it? It should be possible without having to use Squirrel.Windows.

**Comment by iiegor** [comment]
@sindresorhus See https://github.com/atom/electron/issues/3303, apparently fixed. Let's wait for the next release.
