### ISSUE TITLE
Rewrite urls to remove Facebook's redirect

### ISSUE THREAD

**Issue by OmgImAlexis** [sindresorhus/caprine#286]
For example instead of "copy link" showing `https://google.com` it shows this link.

```
https://l.messenger.com/l.php?u=https%3A%2F%2Fgoogle.com%2F&h=ATM85iuo8Kuz-3WhZMFqASMviGKKm6On0v8CdBSD2rO9Vaf6IbC78KK9E_erXrWK_oTnOoxA5FUPDVuAHtuNrWQevJHoKJp7RUOnDBGJk75wuuGaP5395YBvxBMOUwKIG6QieMxBETPOsahb-NI
```

**Comment by chabou** [comment]
Rewriting is currently done when url click/navigate.
Will be great to do the same with copy link

**Comment by kevva** [comment]
Ideally, this would be fixed in https://github.com/sindresorhus/electron-context-menu/issues/14. Otherwise we can listen on the `contextmenu` event in the renderer process and fix the URL there. Problem is that not everything you right click is links with `href` attributes so we might have to check parent elements etc. Not super fast.
