### ISSUE TITLE
Closing Caprine on macOS

### ISSUE THREAD

**Issue by johnolos** [sindresorhus/caprine#288]
I don't have any specifics here (maybe I can dig later), but I think closing caprine on macOS is not done "by the book".

I'm using Amethyst (tiled window manager) for macOS and it re-renders (moves and resizes) windows in a screen whenever one window is closed/moved or otherwise changed.

I guess then Caprine is closed, such window-event Amethyst listens to is never fired off, and the space Caprine filled, stays filled until I force-kill Caprine which sometimes results so that the space re-renders, but not always.

Similar electron-apps, such as Slack, have said window-event fired correctly I am assuming and space re-renders correctly.

(This is a little vague, I know. Again, my assumption is that a particular window-event is not fired which macOS normally receives.)

Edit: Funny enough. If I close Caprine normally, and ask Amethyst to force-render space, it will not fill the space Caprine had. Maybe Caprine is claiming said space even if minimised. Killing Caprine, and then force re-render results in space being filled.

**Comment by Vilscon** [comment]
Gotta look into Amethyst, because if I think I understand you correctly, I like it's functionality.

However, you say 'close' Caprine. Do you mean by clicking the red X in the upper left corner or clicking 'Caprine  → Quit Caprine' on the menu bar? These are (obviously) two different things. 

I'm no developer, just wondering.
