### ISSUE TITLE
Menubar support

### ISSUE THREAD

**Issue by ryanseys** [sindresorhus/caprine#31]
Being a messaging app, it's more useful if it's running all the time so messages can always come in. That being said, it kinda stinks that it has to take up valuable real estate in the dock. What would be nice to have is the option to move the app into the menu bar.

Also, #6 could be solved here by "minimizing" to the menu bar instead of quitting the app entirely.

**Comment by sindresorhus** [comment]
Good suggestion, but not something I need or want.

**Comment by johndbritton** [comment]
I came by to ask for the same feature here, and thought I'd ask again since this issue is from so long ago.

Maybe this is something you've come around to after some more thought as you changed your mind in https://github.com/sindresorhus/caprine/issues/6.

My argument for this feature would be that Caprine as an application that is running all the time takes up space in the app switcher even when it's not actively being used. My reasoning for being able to put the app in the menubar is that I would like for it to be minimally visible unless I get an incoming message / notification.
