### ISSUE TITLE
High memory consumption of CaprineHelper on macOS Sierra

### ISSUE THREAD

**Issue by Rezonansowy** [sindresorhus/caprine#346]
Sometimes CaprineHelper starts to create a high memory usage. This seems to happen even the app is not extensively used. I tested this on macOS Sierra only. The issue is not with Caprine itself but with its Electron helper.

Here's the screenshot:
<img width="492" alt="high memory usage" src="https://user-images.githubusercontent.com/6929363/34419983-e74f80b2-ebd4-11e7-928c-0b7a562ea8c9.png">

---

Caprine 2.9.0
Electron 1.7.9
darwin x64 16.7.0

**Comment by sindresorhus** [comment]
That's probably out of our control, but hopefully will improve when Electron 2.0 is out and we can upgrade to a much more modern Chrome version.

**Comment by Rezonansowy** [comment]
OK, so the way to fix this bug is to wait for Electron 2.0 and make the upgrade.

**Comment by vanshg** [comment]
Just for reference, I compared the memory a Messenger tab was taking up with the memory Caprine was taking up on my machine.
Caprine: 218 MB
Chrome Messenger Tab: 248 MB

This may just be my machine, but I think the memory consumption is a non-issue. (The CPU usage of Caprine is also lower than that of the Chrome messenger tab, which I'm assuming is because no Chrome extensions need to run)

**Comment by sindresorhus** [comment]
Not much we can do about this, unfortunately...

You could try reporting the it to https://github.com/electron/electron

**Comment by jq-iulian33** [comment]
the same issue on macOs Catalina
