### ISSUE TITLE
Preferences don't save on macOS High Sierra

### ISSUE THREAD

**Issue by AwaitingIrindul** [sindresorhus/caprine#369]
Whenever I close Caprine and open it again, I have to reset the preferences as I like. 
Since I haven't touched many parameters, the one I need to reset is 'Enable desktop notifications'. 

I'm on macOS High Sierra (10.13.2) where Caprine version is 2.9.0 (2.9.0.630). 

It is not very inconvenient but if a fix is possible that would be awesome!

**Comment by dusansimic** [comment]
It's the same on Linux (Ubuntu 17.10). I also have to change emoji skin color.

**Comment by cattenbb** [comment]
My desktop notifications keeps disabling itself.

**Comment by sammarcus** [comment]
Hi @dusansimic / @sindresorhus , I see this is a recurring problem in #417 , #420, #386, #414 but on macOS 10.13.4 and Caprine 2.11.0 this issue is still occuring for me, and the preferences are not getting saved. Was the fix primarily for linux or should macOS also be saving this preference now too?

Thank you!

**Comment by dusansimic** [comment]
Hello @sammarcus, this problem will be fixed when #420 gets pulled. It was a loading time problem. This fix will work on any machine. I guess you'll just have to wait for it to get pulled.

**Comment by sammarcus** [comment]
So sorry! Didn't notice the PR was still open. I apologize! Thank you for opening that.
