### ISSUE TITLE
Button for file attachment

### ISSUE THREAD

**Issue by bjarkih1977** [sindresorhus/caprine#387]
No visible option (icon) to attach a file.  There are option for images, videos, gifs etc. but a text file is not an option for example.  This option is available in the inbuilt function on facebook.com.
 

---

Caprine 2.9.0
Electron 1.7.11
linux x64 4.14.15-1-MANJARO

**Comment by 4cm4k1** [comment]
You can attach files by dragging and dropping, but I agree it would be nice to have an icon to click.

**Comment by bjarkih1977** [comment]
I'm not that much of a drag and drop person.

**Comment by sindresorhus** [comment]
The `image` icon button actually supports selecting any file, so this would just be about changing that icon into something more generic that indicates it supports any file.

**Comment by bjarkih1977** [comment]
Button #1 (labeled 'add photos') does not, when clicked, give me the option of selecting text files or any other files than image formats.

**Comment by vogu66** [comment]
The last button does :

![image](https://user-images.githubusercontent.com/24728720/100322821-1a39f200-2fc5-11eb-8791-8dcf3d622230.png)

Just changing the icon to have something more meaningful would do the trick. Or it is not a concern anymore since things changed in 2 years, not sure, but in the second case the issue can be closed.

**Comment by dusansimic** [comment]
As it's already said, the image icon is for selecting files for upload (or Ctrl + T). Currently there are no plans for changing the icon.
