### ISSUE TITLE
Speak Bubble Icon missing

### ISSUE THREAD

**Issue by paulwaldmann** [sindresorhus/caprine#440]
App Icon not shown in sidebar.

![screenshot from 2018-05-03 12-13-16](https://user-images.githubusercontent.com/32001342/39559791-73c9eee8-4ecb-11e8-8fe3-293646fdda43.png)

Should be surely the blue speak bubble.

---

Caprine 2.12.1
Electron 1.8.6
linux x64 4.15.0-20-generic

**Comment by sindresorhus** [comment]
Related to https://github.com/electron-userland/electron-builder/issues/2577

**Comment by gnanet** [comment]
https://github.com/electron-userland/electron-builder/issues/2577#issuecomment-377562602
in the workaround part the small change of `renamed build/icon.png to build/icons/512.png` is a clear win 

otherwise get icns2png 

```
sudo apt-get -y install icnsutils
```
then get the original Icon.icns from github, and spread the icons:

```
cp Icon.icns caprine.icns
icns2png -x caprine.icns
ls -1 *.png | sed -e "s/^\(.*\)_\([0-9]*\)x\([0-9]*\)x32\.png/cp \0 \/usr\/share\/icons\/hicolor\/\2x\3\/apps\/\1.png/g" | bash
/usr/bin/gtk-update-icon-cache /usr/share/icons/hicolor
```
worked like a "charm" for me

**Comment by dusansimic** [comment]
This is fixed in the latest release. Please update Caprine to the latest version.
