### ISSUE TITLE
OAuth/2FA login not working properly

### ISSUE THREAD

**Issue by shawnburke** [sindresorhus/caprine#495]
Happens on OSX, Linux, and Win 10 (I run all three in various places).  Version 2.14.2.

I have code-based 2FA enabled on my account.

1. Open Caprine
2. Enter Email + Password
3. Caprine shows "Please Verify Your Facebook Account / Continue"
4. Click "Continue" => Opens browser
5. Go through "We don't recognize this location flow"
6. Caprine never advances, even after closing browser

On OSX and Linux I was able to workaround by:

- Copy/paste "Continue" link to an incognito window
- Kill and restart Caprine after the flow

I can't get past it on Windows.  

Can probably help debug if you tell me where to look?

**Comment by kvonbredow** [comment]
Seeing the same problem, though I was able to use the workaround on Windows 10 - Version 2.14.2

**Comment by sindresorhus** [comment]
Probably caused by https://github.com/sindresorhus/caprine/commit/ec73bb20aff07d8c07f2ebc883869c16d9f70de9.

I don't have 2FA. Can someone replace https://github.com/sindresorhus/caprine/commit/ec73bb20aff07d8c07f2ebc883869c16d9f70de9#diff-168726dbe96b3ce427e7fedce31bb0bcR315 with `console.log(url);` and check what URL is used for 2FA? Or go to http://messenger.com/, log in with 2FA and check what URLs it uses.

**Comment by kvonbredow** [comment]
I just checked https://messenger.com/, and it sends you to: https://www.facebook.com/checkpoint/start/

**Comment by sindresorhus** [comment]
I did a new release where I tried an untested workaround. Let me know if that made it work: https://github.com/sindresorhus/caprine/releases/tag/v2.15.0

**Comment by kvonbredow** [comment]
Worked for me on both Windows 10 1803 and Ubuntu 16.04, thanks for the quick work!

**Comment by sindresorhus** [comment]
Great :)
