### ISSUE TITLE
Respect Do Not Disturb on macOS

### ISSUE THREAD

**Issue by nikersify** [sindresorhus/caprine#496]
[<img alt="Issuehunt badges" src="https://issuehunt.io/r/sindresorhus/caprine/issues/496/badge.svg" />](https://issuehunt.io/r/sindresorhus/caprine/issues/496)

With the Do Not Disturb mode turned on in Preferences, I'm still getting sound and visual (dock icon bouncing) notifications from Caprine. Would this be possible to fix, so as to Do Not Disturb works as expected with Caprine?

> There is a $30.00 open bounty on this issue. Add more on [Issuehunt](https://issuehunt.io/r/sindresorhus/caprine/issues/496).
> - Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/caprine/) to discover more funded issues.
> - Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on Issuehunt to raise funds.

**Comment by whitecrownclown** [comment]
Hello @sindresorhus, Is there a way to get an event from toggling the macos DND? Otherwise how would you know to update the app? With the current api from https://github.com/sindresorhus/do-not-disturb you can only enable/disable sounds and notifications at the app start. Maybe i'm missing something, but i'll have a PR soon and we can talk more on that.
