### ISSUE TITLE
How to change the size and position of an app on default? 

### ISSUE THREAD

**Issue by cdmjr** [sindresorhus/caprine#497]
I want it on the left side of screen every time I open it because as of now, it is on the center of the screen.

Btw. I'm using Manjaro LXDE as OS.

Is that possible?

**Comment by cawa-93** [comment]
As far as I understand, your operating system should remember the last position and window size. And use each time you run programs

**Comment by sindresorhus** [comment]
@cawa-93 That is unfortunately not supported on Electron by default, so each app has to implement this logic.

We already have this though: https://github.com/sindresorhus/caprine/blob/f670be178980077462b5ddc8b37ffec00847af00/index.js#L363 So something must be broken with it.

**Comment by bland328** [comment]
On my Mojave system, Caprine _(or Electron?)_ behavior regarding initial window size and position is weird:

1. It doesn't _always_ remember window size and position; I haven't been able to find a pattern there.

2. Weirder, if I maximize the window _(whether by Option-clicking the green 'Maximize' button or by manually dragging the edges to touch the menu bar, dock and screen edges)_, quit Caprine and relaunch, the top edge of the window gets moved down a bit _(23 pixels away from the menu bar)_!

![Caprine window size weirdness](https://user-images.githubusercontent.com/8441277/54707543-5853f280-4b0f-11e9-823a-33c87c272e94.jpg)

As for whether Electron or Caprine is causing this, FWIW, the Atom text editor behaves properly.

**Comment by bland328** [comment]
I found a workaround for this, which is likely a big hint as to where the bug is:

1. Set the window to maximum size by Option-clicking the green 'Maximize' window button
2. Hide the Dock _(System Preferences > Dock > Automatically hide...)_
3. Quit Caprine
4. Unhide the Dock
5. Open Caprine

Et voilà--Caprine no longer pushes the top edge of the window away from the menu bar.

**Comment by bland328** [comment]
Now that my dock is hidden, I'm back to fighting it again.

Apparently, either when exiting or loading, either Caprine or Electron is tweaking the height of the window in a misguided effort to make sure it isn't too big.

I say this because on my system, when the Caprine window is maximum size (I am always showing the menu bar, but hiding the dock) and I quit and relaunch, the following happens:

1) The top edge of the window is moved down by the height of the menu bar (meaning the top edge ends up 23 pixels _away from_ the 23-pixel-tall menu bar), and...

2) The bottom edge of the window is moved up by the current height of the dock--even though my dock is hidden.

I don't see this behavior out of any other apps, and don't have any sort of third-party window-manipulation utilities installed.

Hope this is helpful!

**Comment by dusansimic** [comment]
This feature seems to work without issues so I'm closing this report
