### ISSUE TITLE
 [Windows Version] If you try to put  @ (AltGr+2) it will switch conversations

### ISSUE THREAD

**Issue by athousanddetails** [sindresorhus/caprine#539]
[Windows Version] If you try to put  @ (AltGr+2) it will switch conversations. I am using Windows 10 x64, Portuguese Keyboard layout. 

---

Caprine 2.16.0
Electron 2.0.4
win32 x64 10.0.17134

**Comment by sindresorhus** [comment]
// @Smile4ever

**Comment by Smile4ever** [comment]
This is indeed a bug, which was present before but now became apparent. AltGr + 2 on my keyboard layout makes the "at" sign. I will see whether I can submit a pull request that fixes this bug.

**Comment by athousanddetails** [comment]
yeah here to alt gr + 2 makes @ symbol too! And well switches chat windows eheh! 

I also found another bug, 98% of videos play in chat, some just don't do nothing, you can scroll in the timeline of the video but doesn't play fluently neither if you open full screen :) I will test that one out more

**Comment by isness** [comment]
For some users with keyboard layouts other then English this bug is very frustrating because some languages put their non-latin letters (and their capital versions) on number keys, so to get a number or some other sign (like !@#$%^&*()+) we use Alt + (+Shift) + number key. With caprine, this doesn't work, as it always switch conversations.

**Comment by Smile4ever** [comment]
AltGr is wrongly mapped to ControlLeft on Windows:

![afbeelding](https://user-images.githubusercontent.com/544411/43418605-b83c3992-943e-11e8-89b7-cf5a1871ca73.png)

This is a bug in Electron itself. Since Caprine detects Control, it goes ahead to switching conversations.

I tried to check the event on Windows for other indicators that the key pressed is AltGr but I found no parameter that we can use (if you press the real control, it also reports ControlLeft with the same properties). That's why I think it is best that we handle Windows differently, requiring shift on the top row to be used. @sindresorhus would that be okay with you?

I was able to verify that the behaviour on Linux doesn't show. The event data is as I would expect it on Linux:
![virtuallinux](https://user-images.githubusercontent.com/544411/43418327-d3597dd0-943d-11e8-9708-748d936c9d11.png)

I'm unsure for macOS, but since we are handling meta keys there instead of ctrlKey it should be fine there.
