### ISSUE TITLE
crash/support request

### ISSUE THREAD

**Issue by kmddd59** [sindresorhus/caprine#549]
ok you need to have the window open and a message open and have the main window be the messenger right click on a users profile image and try to save it and it will crash as shown in video
also looking for a possible support for screen sharing its an option but says I can't do it on my Mac because I need the facebook plugin for it 

![animated gif-downsized_large](https://user-images.githubusercontent.com/5413229/43616031-6a6a951e-966f-11e8-9a71-e4ffd92f67c0.gif)

---

Caprine 2.16.0
Electron 2.0.4
darwin x64 18.0.0

**Comment by dusansimic** [comment]
About the image saving, on Linux the image is saved into Downloads folder but there is no indication that it happened, so there's no crash.

**Comment by kmddd59** [comment]
I’m on macOS  though

**Comment by dusansimic** [comment]
Is there anyone else who has this same issue on macOS?

**Comment by mquevill** [comment]
In recent versions, right-clicking the profile picture does not even bring up a drop-down menu.

**Comment by dusansimic** [comment]
I'll close this issue since it's stale and there seem to be no additional reports of this problem lately.

If context menu on right clicking an image is expected (maybe it should be) I think that should be reported separately. I'd like to wait until upgrading to Electron 12 (and with that upgrading the electron-context-menu library) before this the context menu issue is addressed.
