### ISSUE TITLE
[RESOLVED] Plasma 5 - Icon tray just shows Toggle/Quit

### ISSUE THREAD

**Issue by sagittarius06** [sindresorhus/caprine#585]
On several plasma 5 desktops, I had a Caprine icon just showing Toggle/Quit that was very frustrating. The trick is to remove some packages on your distro: libindicator-gtk2 libindicator-gtk3 (on archlinux/manjaro or libappindicator on others).

**Comment by alekksander** [comment]
so how does it looks like now? could You post screenshot? i can't remove libindicator3-7 due to few apps that want to get out with it

**Comment by yermulnik** [comment]
@alekksander same here and +1 to a question

**Comment by sagittarius06** [comment]
There, it seems it's relative to electron: https://github.com/electron/electron/issues/6773

**Comment by vanushwashere** [comment]
Google Chrome uses libindicator3-1, so I don't delete that, but that opening menu with toggle and quit on left click is driving me crazy :/

**Comment by dusansimic** [comment]
Electron uses libappindicator on all distros that don't support gtkstatusindicator. Since libappindicator shows the tray menu as described and it ignores the click event, there's nothing we can do here. On [this](https://www.electronjs.org/docs/api/tray#class-tray) docs page you can see under platform limitations what I just described.
