### ISSUE TITLE
Start minimized on Linux

### ISSUE THREAD

**Issue by cwilli34** [sindresorhus/caprine#64]
#52 So it is not possible, or easily possible, to start Caprine minimized to the tray in Linux.  This should be a option in settings/preferences, or at least available in the command line so it is easier to accomplish.

**Comment by sindresorhus** [comment]
Already possible on OS X, but I'm to adding a CLI flag for it on Linux, but not interested in any GUI options. PR welcome :)

**Comment by cwilli34** [comment]
Yes, even a CLI flag would be fine for me because I can at least put that flag in the startup command to minimize it to tray.  Better than nothing if you aren't wanting to add it to the preferences.

**Comment by TamasBarta** [comment]
Why is this closed? The option can still only start Caprine minimized to the taskbar, not to the tray.
This is also mentioned in #60 

I'm no Electron expert, but trying to judge from the diff in #126, I'd say you only have to skip calling `.show()`. Both features may be useful, but since we have a tray icon, that cannot be turned off, it's probably best to minimize to tray, which actually means not showing the window at all.

What do you think? Do you have anything serious against this approach?

**Comment by sindresorhus** [comment]
Yeah, minimizing to tray makes more sense on Windows/Linux.
