### ISSUE TITLE
Dark mode greyed out

### ISSUE THREAD

**Issue by slayerbrk** [sindresorhus/caprine#733]
Dark mode appears greyed out and can not be enabled.

**Comment by CvX** [comment]
You probably have the "View > Follow System Appearance" enabled. If you want to enable the "Dark Mode" independently of system theme setting, disable that first.

@sindresorhus, maybe it would be better to have the "Follow System Appearance" always enabled, and just toggle it off if you change the "Dark Mode" setting? Dunno which way is less confusing. 🤷‍♂️

**Comment by 19majkel94** [comment]
I have dark mode enabled in Windows 10 settings but the dark mode is still grayed out.

![image](https://user-images.githubusercontent.com/10618781/51424839-c6457180-1bd3-11e9-9a98-1955c3322a34.png)

I also don't have the "Follow system apperance" options 😕

**Comment by janosorcsik** [comment]
The "Follow System Appearance" shows only on MacOS.
The "Dark mode" enabled if the "followSystemAppearance" config is false, but it is always true in config.
The "followSystemAppearance" needs to true only on MacOS.

**Comment by dhuertasanchez** [comment]
The same thing happens to me, the dark mode is not activated, it happens to me in Linux, Mac and Windows, the strange thing is that a couple of days ago it worked correctly, but then the color changed to a gray one and with the texts in white color so that can not be distinguished, and in the conversations the conversation panel is shown in dark mode, but the contacts panel keeps the gray color with white texts...
![darkmode_broken](https://user-images.githubusercontent.com/8291300/51932872-af6a0080-23c5-11e9-844e-852ee8489f32.png)

**Comment by CvX** [comment]
@dhuertasanchez This issue is tracked in #712.
The current workaround is to disable vibrancy "View -> Vibrancy -> No Vibrancy"

**Comment by dhuertasanchez** [comment]
@CvX Hi, thank you, yep, i have already deactivated vibrancy, although in Linux and Windows the error persists with the dark mode, something strange happens there, I will have to continue with the light mode

**Comment by CvX** [comment]
I'll look into dark mode on Windows tomorrow. Thanks for the info!
