### ISSUE TITLE
Use Prettier

### ISSUE THREAD

**Issue by felixfbecker** [sindresorhus/caprine#736]
When contributing, a non-zero amount of my time was spent fixing formatting issues that xo would or would not complain about. It would be a lot more fun to contribute if an automatic formatter like Prettier was used.

**Comment by CvX** [comment]
Adding prettier was on my TODO list. 😄Prettier's value increases with each new contributor, as every one of us has a slightly different idea about how to format the code. 😉 

Btw. since this project uses xo (and doesn't have its own .eslintrc.js) some editors (atom/vscode) don't automatically lint the code. Turns out there are extensions specifically for xo, like https://atom.io/packages/linter-xo. TIL 😉
