### ISSUE TITLE
Allow mention by nickname

### ISSUE THREAD

**Issue by joshc133** [sindresorhus/caprine#858]
#### Description:
Official Messenger app for iOS allows mentioning a person (in group chat) by their chat nickname.  I'm requesting this same feature for Caprine. 

#### Scenario:
Let's say I'm in a group chat with 3 other people (**Actual name - `NickName`**):
* John Smith - `JohnnyBoy`
* John Deer - `TheDeer`
* John Random - `Rando`

On both official iOS Messenger app and Caprine, I can start typing `TheDeer` (John Deer's nickname), and it recognizes that I'm trying to mention `John Deer`.  On iOS when I tap the mention pop-up, it would populate my chat message with `@TheDeer`, however on Caprine my chat message would be populated with `@John Deer`.

**Comment by CvX** [comment]
That sounds reasonable, but it's how [messenger.com](https://messenger.com) works now, and I don't think it would be feasible (or maybe even not possible at all) to work around this limitation.

**Comment by dusansimic** [comment]
I agree. It might be possible to do it but it would require us to scrape user nicknames and real names, track what user inputs and if the user starts typing the nickname, show the list of nicknames and once a nickname is selected replace it with the username link. This would require a lot of moving parts and it would break easily if UI changes. I'll close this since it's better to let Facebook implement it on their side.
