### ISSUE TITLE
Caprine gives an "X messaged you is ready" when a new message is received

### ISSUE THREAD

**Issue by Jont828** [sindresorhus/caprine#862]
Instead of just the normal notification with the person's name, picture, and message, first I get a notification from Caprine with the messenger icon saying "X messaged you is ready." Once I close that notification, I can get the notification with the actual message. This didn't seem to happen until the past couple days. I've tried to use Gnome extensions like NoAnnoyance, but it didn't seem to work. Is this an issue with Caprine or Gnome shell? Thanks!

**Comment by SolarLiner** [comment]
This isn't a bug from GNOME since, by design, windows can't steal focus - instead, when they request it, GNOME shows the "window is ready" notification, that you can click to accept the focus. This is similar IIRC to macOS and Windows which either make the application window bounce in the dock or blinks the taskbar entry, respectively; therefore applications use this "request for focus" as a way to direct attention to the user - but in GNOME it instead brings up a notification.

I don't know that this is what Caprine is doing, but I would assume it is given the behavior you reported.

I think there is an option to not request focus on new messages in the menu bar that you can disable.

**Comment by Cornul11** [comment]
This is a very strange behavior. You would expect Caprine to show the message itself in the notification text, or at least who messaged you, in order to make the notifications useful.

**Comment by dusansimic** [comment]
According to the description, this is not a Caprine issue, rather a GNOME feature which you don't really want to happen. After some research, it seems like [Window is Ready - Notification Remover](https://extensions.gnome.org/extension/1007/window-is-ready-notification-remover/) extension should do the trick.
