### ISSUE TITLE
Can't respond to calls

### ISSUE THREAD

**Issue by iseulde** [sindresorhus/caprine#92]
On OS X 10.11.4 (15E65).

When there's a call, a notification appears, and when clicked, a new tab opens in the browser, the call is automatically rejected, and I am offered to start a call with that person.

**Comment by sindresorhus** [comment]
I just did a new version with an upgrade Chrome version. Not really sure what causes this though...

Can you try it? https://github.com/sindresorhus/caprine/releases/tag/1.4.0

**Comment by crshlx** [comment]
Same problem here, because the app open a tab in the default system browser (in my case, safari) and if this browser is not supported by video/audio calls from messenger (safari again), the call is rejected.

The best solution is to activate the ability of using calls inside the app/electron with chrome plugins (like the "messenger for desktop" app).

ps: Sorry for my vera bad english...

**Comment by vitalykorolev** [comment]
Same here. Can't make calls either. Could it be due to inability to allow the use of microphone and camera?

**Comment by manicmarvin** [comment]
I think this is an important issue. If the call functionality can be implemented in Electron (both audio and video or just audio) it should be done, but until such time, the buttons for video and audio calls should be removed. Then the behaviour won't seem buggy, but will appear intended.

**Comment by manicmarvin** [comment]
Also, @iseulde can we change the issue name from 'Can't Respond to Calls' to **'Broken Call Functionality'** or something that expresses who this is a larger systemic problem?
