### ISSUE TITLE
Attaching/Drag and drop images result in error

### ISSUE THREAD

**Issue by massayoshi** [sindresorhus/caprine#997]
Tried attaching an image and it gave me this error. Drag and drop caused the same thing.

![Screen Shot 2019-07-15 at 15 02 31](https://user-images.githubusercontent.com/609562/61237887-dcab3080-a711-11e9-902b-1cd1de7be2d7.png)

**Comment by CvX** [comment]
Does this happen with that image only, or with other images too?

Messenger's message composer ([Draft.js](https://github.com/facebook/draft-js)) is occasionally unreliable, but I don't think we can do much about it (other than fixing this particular issue upstream, if the issue is reproducible there too).

**Comment by massayoshi** [comment]
@CvX Tried with a variety of images files and the result is the same. However, just opened messenger.com on Chrome and Safari and the error still occurs.

Thanks!
